/* This C file is generated by NIT to compile module factory. */
#include "factory._sep.h"
val_t factory___Fabrique___creerPolygone(val_t p0, val_t p1){
  struct {struct stack_frame_t me; val_t MORE_REG[8];} fra;
  val_t REGB0;
  val_t REGB1;
  val_t REGB2;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_factory;
  fra.me.line = 6;
  fra.me.meth = LOCATE_factory___Fabrique___creerPolygone;
  fra.me.has_broke = 0;
  fra.me.REG_size = 9;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[3] = NIT_NULL;
  fra.me.REG[4] = NIT_NULL;
  fra.me.REG[5] = NIT_NULL;
  fra.me.REG[6] = NIT_NULL;
  fra.me.REG[7] = NIT_NULL;
  fra.me.REG[8] = NIT_NULL;
  fra.me.REG[0] = p0;
  fra.me.REG[1] = p1;
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:23 */
  REGB0 = TAG_Bool(ATTR_array___AbstractArrayRead____length(fra.me.REG[1])!=NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_length", LOCATE_array, 23);
  }
  REGB0 = ATTR_array___AbstractArrayRead____length(fra.me.REG[1]);
  /* ./factory.nit:9 */
  REGB1 = TAG_Int(3);
  REGB2 = TAG_Bool(IS_EQUAL_OO(REGB0,REGB1));
  if (UNTAG_Bool(REGB2)) {
  } else {
    /* /Users/tony/Projects/nit/lib/standard//kernel.nit:207 */
    REGB1 = TAG_Bool((REGB0)==(REGB1));
    /* ./factory.nit:9 */
    REGB2 = REGB1;
  }
  if (UNTAG_Bool(REGB2)) {
    /* ./factory.nit:10 */
    fra.me.REG[0] = NEW_Triangle_polygone___Triangle___init(fra.me.REG[1]);
    goto label1;
  } else {
    /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:23 */
    REGB2 = TAG_Bool(ATTR_array___AbstractArrayRead____length(fra.me.REG[1])!=NIT_NULL);
    if (UNTAG_Bool(REGB2)) {
    } else {
      nit_abort("Uninitialized attribute %s", "_length", LOCATE_array, 23);
    }
    REGB2 = ATTR_array___AbstractArrayRead____length(fra.me.REG[1]);
    /* ./factory.nit:13 */
    REGB1 = TAG_Int(4);
    REGB0 = TAG_Bool(IS_EQUAL_OO(REGB2,REGB1));
    if (UNTAG_Bool(REGB0)) {
    } else {
      /* /Users/tony/Projects/nit/lib/standard//kernel.nit:207 */
      REGB1 = TAG_Bool((REGB2)==(REGB1));
      /* ./factory.nit:13 */
      REGB0 = REGB1;
    }
    if (UNTAG_Bool(REGB0)) {
      /* ./factory.nit:14 */
      REGB0 = TAG_Int(2);
      fra.me.REG[2] = NEW_Array_array___Array___with_capacity(REGB0);
      REGB0 = TAG_Int(0);
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:243 */
      fra.me.REG[3] = fra.me.REG[1];
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
      REGB1 = TAG_Int(0);
      /* /Users/tony/Projects/nit/lib/standard//kernel.nit:213 */
      REGB1 = TAG_Bool(UNTAG_Int(REGB0)>=UNTAG_Int(REGB1));
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
      if (UNTAG_Bool(REGB1)) {
        REGB1 = TAG_Bool(ATTR_array___AbstractArrayRead____length(fra.me.REG[3])!=NIT_NULL);
        if (UNTAG_Bool(REGB1)) {
        } else {
          nit_abort("Uninitialized attribute %s", "_length", LOCATE_array, 245);
        }
        REGB1 = ATTR_array___AbstractArrayRead____length(fra.me.REG[3]);
        /* /Users/tony/Projects/nit/lib/standard//kernel.nit:212 */
        REGB1 = TAG_Bool(UNTAG_Int(REGB0)<UNTAG_Int(REGB1));
      } else {
        /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
        REGB2 = TAG_Bool(false);
        REGB1 = REGB2;
      }
      if (UNTAG_Bool(REGB1)) {
      } else {
        nit_abort("Assert %s  failed", "'index'", LOCATE_array, 245);
      }
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
      fra.me.REG[3] = ATTR_array___Array____items(fra.me.REG[3]);
      REGB1 = TAG_Bool(fra.me.REG[3]==NIT_NULL);
      if (UNTAG_Bool(REGB1)) {
        nit_abort("Reciever is null", NULL, LOCATE_array, 246);
      }
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:654 */
      fra.me.REG[3] = ((Nit_NativeArray)fra.me.REG[3])->val[UNTAG_Int(REGB0)];
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
      goto label2;
      label2: while(0);
      /* ./factory.nit:14 */
      CALL_abstract_collection___SimpleCollection___add(fra.me.REG[2])(fra.me.REG[2], fra.me.REG[3]);
      REGB0 = TAG_Int(1);
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:243 */
      fra.me.REG[3] = fra.me.REG[1];
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
      REGB1 = TAG_Int(0);
      /* /Users/tony/Projects/nit/lib/standard//kernel.nit:213 */
      REGB1 = TAG_Bool(UNTAG_Int(REGB0)>=UNTAG_Int(REGB1));
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
      if (UNTAG_Bool(REGB1)) {
        REGB1 = TAG_Bool(ATTR_array___AbstractArrayRead____length(fra.me.REG[3])!=NIT_NULL);
        if (UNTAG_Bool(REGB1)) {
        } else {
          nit_abort("Uninitialized attribute %s", "_length", LOCATE_array, 245);
        }
        REGB1 = ATTR_array___AbstractArrayRead____length(fra.me.REG[3]);
        /* /Users/tony/Projects/nit/lib/standard//kernel.nit:212 */
        REGB1 = TAG_Bool(UNTAG_Int(REGB0)<UNTAG_Int(REGB1));
      } else {
        /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
        REGB2 = TAG_Bool(false);
        REGB1 = REGB2;
      }
      if (UNTAG_Bool(REGB1)) {
      } else {
        nit_abort("Assert %s  failed", "'index'", LOCATE_array, 245);
      }
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
      fra.me.REG[3] = ATTR_array___Array____items(fra.me.REG[3]);
      REGB1 = TAG_Bool(fra.me.REG[3]==NIT_NULL);
      if (UNTAG_Bool(REGB1)) {
        nit_abort("Reciever is null", NULL, LOCATE_array, 246);
      }
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:654 */
      fra.me.REG[3] = ((Nit_NativeArray)fra.me.REG[3])->val[UNTAG_Int(REGB0)];
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
      goto label3;
      label3: while(0);
      /* ./factory.nit:14 */
      CALL_abstract_collection___SimpleCollection___add(fra.me.REG[2])(fra.me.REG[2], fra.me.REG[3]);
      fra.me.REG[2] = NEW_Segment_figure___Segment___init(fra.me.REG[2]);
      /* ./factory.nit:15 */
      REGB0 = TAG_Int(2);
      fra.me.REG[3] = NEW_Array_array___Array___with_capacity(REGB0);
      REGB0 = TAG_Int(1);
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:243 */
      fra.me.REG[4] = fra.me.REG[1];
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
      REGB1 = TAG_Int(0);
      /* /Users/tony/Projects/nit/lib/standard//kernel.nit:213 */
      REGB1 = TAG_Bool(UNTAG_Int(REGB0)>=UNTAG_Int(REGB1));
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
      if (UNTAG_Bool(REGB1)) {
        REGB1 = TAG_Bool(ATTR_array___AbstractArrayRead____length(fra.me.REG[4])!=NIT_NULL);
        if (UNTAG_Bool(REGB1)) {
        } else {
          nit_abort("Uninitialized attribute %s", "_length", LOCATE_array, 245);
        }
        REGB1 = ATTR_array___AbstractArrayRead____length(fra.me.REG[4]);
        /* /Users/tony/Projects/nit/lib/standard//kernel.nit:212 */
        REGB1 = TAG_Bool(UNTAG_Int(REGB0)<UNTAG_Int(REGB1));
      } else {
        /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
        REGB2 = TAG_Bool(false);
        REGB1 = REGB2;
      }
      if (UNTAG_Bool(REGB1)) {
      } else {
        nit_abort("Assert %s  failed", "'index'", LOCATE_array, 245);
      }
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
      fra.me.REG[4] = ATTR_array___Array____items(fra.me.REG[4]);
      REGB1 = TAG_Bool(fra.me.REG[4]==NIT_NULL);
      if (UNTAG_Bool(REGB1)) {
        nit_abort("Reciever is null", NULL, LOCATE_array, 246);
      }
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:654 */
      fra.me.REG[4] = ((Nit_NativeArray)fra.me.REG[4])->val[UNTAG_Int(REGB0)];
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
      goto label4;
      label4: while(0);
      /* ./factory.nit:15 */
      CALL_abstract_collection___SimpleCollection___add(fra.me.REG[3])(fra.me.REG[3], fra.me.REG[4]);
      REGB0 = TAG_Int(2);
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:243 */
      fra.me.REG[4] = fra.me.REG[1];
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
      REGB1 = TAG_Int(0);
      /* /Users/tony/Projects/nit/lib/standard//kernel.nit:213 */
      REGB1 = TAG_Bool(UNTAG_Int(REGB0)>=UNTAG_Int(REGB1));
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
      if (UNTAG_Bool(REGB1)) {
        REGB1 = TAG_Bool(ATTR_array___AbstractArrayRead____length(fra.me.REG[4])!=NIT_NULL);
        if (UNTAG_Bool(REGB1)) {
        } else {
          nit_abort("Uninitialized attribute %s", "_length", LOCATE_array, 245);
        }
        REGB1 = ATTR_array___AbstractArrayRead____length(fra.me.REG[4]);
        /* /Users/tony/Projects/nit/lib/standard//kernel.nit:212 */
        REGB1 = TAG_Bool(UNTAG_Int(REGB0)<UNTAG_Int(REGB1));
      } else {
        /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
        REGB2 = TAG_Bool(false);
        REGB1 = REGB2;
      }
      if (UNTAG_Bool(REGB1)) {
      } else {
        nit_abort("Assert %s  failed", "'index'", LOCATE_array, 245);
      }
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
      fra.me.REG[4] = ATTR_array___Array____items(fra.me.REG[4]);
      REGB1 = TAG_Bool(fra.me.REG[4]==NIT_NULL);
      if (UNTAG_Bool(REGB1)) {
        nit_abort("Reciever is null", NULL, LOCATE_array, 246);
      }
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:654 */
      fra.me.REG[4] = ((Nit_NativeArray)fra.me.REG[4])->val[UNTAG_Int(REGB0)];
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
      goto label5;
      label5: while(0);
      /* ./factory.nit:15 */
      CALL_abstract_collection___SimpleCollection___add(fra.me.REG[3])(fra.me.REG[3], fra.me.REG[4]);
      fra.me.REG[3] = NEW_Segment_figure___Segment___init(fra.me.REG[3]);
      /* ./factory.nit:16 */
      REGB0 = TAG_Int(2);
      fra.me.REG[4] = NEW_Array_array___Array___with_capacity(REGB0);
      REGB0 = TAG_Int(2);
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:243 */
      fra.me.REG[5] = fra.me.REG[1];
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
      REGB1 = TAG_Int(0);
      /* /Users/tony/Projects/nit/lib/standard//kernel.nit:213 */
      REGB1 = TAG_Bool(UNTAG_Int(REGB0)>=UNTAG_Int(REGB1));
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
      if (UNTAG_Bool(REGB1)) {
        REGB1 = TAG_Bool(ATTR_array___AbstractArrayRead____length(fra.me.REG[5])!=NIT_NULL);
        if (UNTAG_Bool(REGB1)) {
        } else {
          nit_abort("Uninitialized attribute %s", "_length", LOCATE_array, 245);
        }
        REGB1 = ATTR_array___AbstractArrayRead____length(fra.me.REG[5]);
        /* /Users/tony/Projects/nit/lib/standard//kernel.nit:212 */
        REGB1 = TAG_Bool(UNTAG_Int(REGB0)<UNTAG_Int(REGB1));
      } else {
        /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
        REGB2 = TAG_Bool(false);
        REGB1 = REGB2;
      }
      if (UNTAG_Bool(REGB1)) {
      } else {
        nit_abort("Assert %s  failed", "'index'", LOCATE_array, 245);
      }
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
      fra.me.REG[5] = ATTR_array___Array____items(fra.me.REG[5]);
      REGB1 = TAG_Bool(fra.me.REG[5]==NIT_NULL);
      if (UNTAG_Bool(REGB1)) {
        nit_abort("Reciever is null", NULL, LOCATE_array, 246);
      }
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:654 */
      fra.me.REG[5] = ((Nit_NativeArray)fra.me.REG[5])->val[UNTAG_Int(REGB0)];
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
      goto label6;
      label6: while(0);
      /* ./factory.nit:16 */
      CALL_abstract_collection___SimpleCollection___add(fra.me.REG[4])(fra.me.REG[4], fra.me.REG[5]);
      REGB0 = TAG_Int(3);
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:243 */
      fra.me.REG[5] = fra.me.REG[1];
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
      REGB1 = TAG_Int(0);
      /* /Users/tony/Projects/nit/lib/standard//kernel.nit:213 */
      REGB1 = TAG_Bool(UNTAG_Int(REGB0)>=UNTAG_Int(REGB1));
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
      if (UNTAG_Bool(REGB1)) {
        REGB1 = TAG_Bool(ATTR_array___AbstractArrayRead____length(fra.me.REG[5])!=NIT_NULL);
        if (UNTAG_Bool(REGB1)) {
        } else {
          nit_abort("Uninitialized attribute %s", "_length", LOCATE_array, 245);
        }
        REGB1 = ATTR_array___AbstractArrayRead____length(fra.me.REG[5]);
        /* /Users/tony/Projects/nit/lib/standard//kernel.nit:212 */
        REGB1 = TAG_Bool(UNTAG_Int(REGB0)<UNTAG_Int(REGB1));
      } else {
        /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
        REGB2 = TAG_Bool(false);
        REGB1 = REGB2;
      }
      if (UNTAG_Bool(REGB1)) {
      } else {
        nit_abort("Assert %s  failed", "'index'", LOCATE_array, 245);
      }
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
      fra.me.REG[5] = ATTR_array___Array____items(fra.me.REG[5]);
      REGB1 = TAG_Bool(fra.me.REG[5]==NIT_NULL);
      if (UNTAG_Bool(REGB1)) {
        nit_abort("Reciever is null", NULL, LOCATE_array, 246);
      }
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:654 */
      fra.me.REG[5] = ((Nit_NativeArray)fra.me.REG[5])->val[UNTAG_Int(REGB0)];
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
      goto label7;
      label7: while(0);
      /* ./factory.nit:16 */
      CALL_abstract_collection___SimpleCollection___add(fra.me.REG[4])(fra.me.REG[4], fra.me.REG[5]);
      fra.me.REG[4] = NEW_Segment_figure___Segment___init(fra.me.REG[4]);
      /* ./factory.nit:17 */
      REGB0 = TAG_Int(2);
      fra.me.REG[5] = NEW_Array_array___Array___with_capacity(REGB0);
      REGB0 = TAG_Int(3);
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:243 */
      fra.me.REG[6] = fra.me.REG[1];
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
      REGB1 = TAG_Int(0);
      /* /Users/tony/Projects/nit/lib/standard//kernel.nit:213 */
      REGB1 = TAG_Bool(UNTAG_Int(REGB0)>=UNTAG_Int(REGB1));
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
      if (UNTAG_Bool(REGB1)) {
        REGB1 = TAG_Bool(ATTR_array___AbstractArrayRead____length(fra.me.REG[6])!=NIT_NULL);
        if (UNTAG_Bool(REGB1)) {
        } else {
          nit_abort("Uninitialized attribute %s", "_length", LOCATE_array, 245);
        }
        REGB1 = ATTR_array___AbstractArrayRead____length(fra.me.REG[6]);
        /* /Users/tony/Projects/nit/lib/standard//kernel.nit:212 */
        REGB1 = TAG_Bool(UNTAG_Int(REGB0)<UNTAG_Int(REGB1));
      } else {
        /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
        REGB2 = TAG_Bool(false);
        REGB1 = REGB2;
      }
      if (UNTAG_Bool(REGB1)) {
      } else {
        nit_abort("Assert %s  failed", "'index'", LOCATE_array, 245);
      }
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
      fra.me.REG[6] = ATTR_array___Array____items(fra.me.REG[6]);
      REGB1 = TAG_Bool(fra.me.REG[6]==NIT_NULL);
      if (UNTAG_Bool(REGB1)) {
        nit_abort("Reciever is null", NULL, LOCATE_array, 246);
      }
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:654 */
      fra.me.REG[6] = ((Nit_NativeArray)fra.me.REG[6])->val[UNTAG_Int(REGB0)];
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
      goto label8;
      label8: while(0);
      /* ./factory.nit:17 */
      CALL_abstract_collection___SimpleCollection___add(fra.me.REG[5])(fra.me.REG[5], fra.me.REG[6]);
      REGB0 = TAG_Int(0);
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:243 */
      fra.me.REG[6] = fra.me.REG[1];
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
      REGB1 = TAG_Int(0);
      /* /Users/tony/Projects/nit/lib/standard//kernel.nit:213 */
      REGB1 = TAG_Bool(UNTAG_Int(REGB0)>=UNTAG_Int(REGB1));
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
      if (UNTAG_Bool(REGB1)) {
        REGB1 = TAG_Bool(ATTR_array___AbstractArrayRead____length(fra.me.REG[6])!=NIT_NULL);
        if (UNTAG_Bool(REGB1)) {
        } else {
          nit_abort("Uninitialized attribute %s", "_length", LOCATE_array, 245);
        }
        REGB1 = ATTR_array___AbstractArrayRead____length(fra.me.REG[6]);
        /* /Users/tony/Projects/nit/lib/standard//kernel.nit:212 */
        REGB1 = TAG_Bool(UNTAG_Int(REGB0)<UNTAG_Int(REGB1));
      } else {
        /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
        REGB2 = TAG_Bool(false);
        REGB1 = REGB2;
      }
      if (UNTAG_Bool(REGB1)) {
      } else {
        nit_abort("Assert %s  failed", "'index'", LOCATE_array, 245);
      }
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
      fra.me.REG[6] = ATTR_array___Array____items(fra.me.REG[6]);
      REGB1 = TAG_Bool(fra.me.REG[6]==NIT_NULL);
      if (UNTAG_Bool(REGB1)) {
        nit_abort("Reciever is null", NULL, LOCATE_array, 246);
      }
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:654 */
      fra.me.REG[6] = ((Nit_NativeArray)fra.me.REG[6])->val[UNTAG_Int(REGB0)];
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
      goto label9;
      label9: while(0);
      /* ./factory.nit:17 */
      CALL_abstract_collection___SimpleCollection___add(fra.me.REG[5])(fra.me.REG[5], fra.me.REG[6]);
      fra.me.REG[5] = NEW_Segment_figure___Segment___init(fra.me.REG[5]);
      /* ./factory.nit:18 */
      REGB0 = TAG_Int(2);
      fra.me.REG[6] = NEW_Array_array___Array___with_capacity(REGB0);
      REGB0 = TAG_Int(0);
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:243 */
      fra.me.REG[7] = fra.me.REG[1];
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
      REGB1 = TAG_Int(0);
      /* /Users/tony/Projects/nit/lib/standard//kernel.nit:213 */
      REGB1 = TAG_Bool(UNTAG_Int(REGB0)>=UNTAG_Int(REGB1));
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
      if (UNTAG_Bool(REGB1)) {
        REGB1 = TAG_Bool(ATTR_array___AbstractArrayRead____length(fra.me.REG[7])!=NIT_NULL);
        if (UNTAG_Bool(REGB1)) {
        } else {
          nit_abort("Uninitialized attribute %s", "_length", LOCATE_array, 245);
        }
        REGB1 = ATTR_array___AbstractArrayRead____length(fra.me.REG[7]);
        /* /Users/tony/Projects/nit/lib/standard//kernel.nit:212 */
        REGB1 = TAG_Bool(UNTAG_Int(REGB0)<UNTAG_Int(REGB1));
      } else {
        /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
        REGB2 = TAG_Bool(false);
        REGB1 = REGB2;
      }
      if (UNTAG_Bool(REGB1)) {
      } else {
        nit_abort("Assert %s  failed", "'index'", LOCATE_array, 245);
      }
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
      fra.me.REG[7] = ATTR_array___Array____items(fra.me.REG[7]);
      REGB1 = TAG_Bool(fra.me.REG[7]==NIT_NULL);
      if (UNTAG_Bool(REGB1)) {
        nit_abort("Reciever is null", NULL, LOCATE_array, 246);
      }
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:654 */
      fra.me.REG[7] = ((Nit_NativeArray)fra.me.REG[7])->val[UNTAG_Int(REGB0)];
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
      goto label10;
      label10: while(0);
      /* ./factory.nit:18 */
      CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[7]);
      REGB0 = TAG_Int(2);
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:243 */
      fra.me.REG[7] = fra.me.REG[1];
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
      REGB1 = TAG_Int(0);
      /* /Users/tony/Projects/nit/lib/standard//kernel.nit:213 */
      REGB1 = TAG_Bool(UNTAG_Int(REGB0)>=UNTAG_Int(REGB1));
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
      if (UNTAG_Bool(REGB1)) {
        REGB1 = TAG_Bool(ATTR_array___AbstractArrayRead____length(fra.me.REG[7])!=NIT_NULL);
        if (UNTAG_Bool(REGB1)) {
        } else {
          nit_abort("Uninitialized attribute %s", "_length", LOCATE_array, 245);
        }
        REGB1 = ATTR_array___AbstractArrayRead____length(fra.me.REG[7]);
        /* /Users/tony/Projects/nit/lib/standard//kernel.nit:212 */
        REGB1 = TAG_Bool(UNTAG_Int(REGB0)<UNTAG_Int(REGB1));
      } else {
        /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
        REGB2 = TAG_Bool(false);
        REGB1 = REGB2;
      }
      if (UNTAG_Bool(REGB1)) {
      } else {
        nit_abort("Assert %s  failed", "'index'", LOCATE_array, 245);
      }
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
      fra.me.REG[7] = ATTR_array___Array____items(fra.me.REG[7]);
      REGB1 = TAG_Bool(fra.me.REG[7]==NIT_NULL);
      if (UNTAG_Bool(REGB1)) {
        nit_abort("Reciever is null", NULL, LOCATE_array, 246);
      }
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:654 */
      fra.me.REG[7] = ((Nit_NativeArray)fra.me.REG[7])->val[UNTAG_Int(REGB0)];
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
      goto label11;
      label11: while(0);
      /* ./factory.nit:18 */
      CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[7]);
      fra.me.REG[6] = NEW_Segment_figure___Segment___init(fra.me.REG[6]);
      /* ./factory.nit:19 */
      REGB0 = TAG_Int(2);
      fra.me.REG[7] = NEW_Array_array___Array___with_capacity(REGB0);
      REGB0 = TAG_Int(1);
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:243 */
      fra.me.REG[8] = fra.me.REG[1];
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
      REGB1 = TAG_Int(0);
      /* /Users/tony/Projects/nit/lib/standard//kernel.nit:213 */
      REGB1 = TAG_Bool(UNTAG_Int(REGB0)>=UNTAG_Int(REGB1));
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
      if (UNTAG_Bool(REGB1)) {
        REGB1 = TAG_Bool(ATTR_array___AbstractArrayRead____length(fra.me.REG[8])!=NIT_NULL);
        if (UNTAG_Bool(REGB1)) {
        } else {
          nit_abort("Uninitialized attribute %s", "_length", LOCATE_array, 245);
        }
        REGB1 = ATTR_array___AbstractArrayRead____length(fra.me.REG[8]);
        /* /Users/tony/Projects/nit/lib/standard//kernel.nit:212 */
        REGB1 = TAG_Bool(UNTAG_Int(REGB0)<UNTAG_Int(REGB1));
      } else {
        /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
        REGB2 = TAG_Bool(false);
        REGB1 = REGB2;
      }
      if (UNTAG_Bool(REGB1)) {
      } else {
        nit_abort("Assert %s  failed", "'index'", LOCATE_array, 245);
      }
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
      fra.me.REG[8] = ATTR_array___Array____items(fra.me.REG[8]);
      REGB1 = TAG_Bool(fra.me.REG[8]==NIT_NULL);
      if (UNTAG_Bool(REGB1)) {
        nit_abort("Reciever is null", NULL, LOCATE_array, 246);
      }
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:654 */
      fra.me.REG[8] = ((Nit_NativeArray)fra.me.REG[8])->val[UNTAG_Int(REGB0)];
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
      goto label12;
      label12: while(0);
      /* ./factory.nit:19 */
      CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[8]);
      REGB0 = TAG_Int(3);
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:243 */
      fra.me.REG[8] = fra.me.REG[1];
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
      REGB1 = TAG_Int(0);
      /* /Users/tony/Projects/nit/lib/standard//kernel.nit:213 */
      REGB1 = TAG_Bool(UNTAG_Int(REGB0)>=UNTAG_Int(REGB1));
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
      if (UNTAG_Bool(REGB1)) {
        REGB1 = TAG_Bool(ATTR_array___AbstractArrayRead____length(fra.me.REG[8])!=NIT_NULL);
        if (UNTAG_Bool(REGB1)) {
        } else {
          nit_abort("Uninitialized attribute %s", "_length", LOCATE_array, 245);
        }
        REGB1 = ATTR_array___AbstractArrayRead____length(fra.me.REG[8]);
        /* /Users/tony/Projects/nit/lib/standard//kernel.nit:212 */
        REGB1 = TAG_Bool(UNTAG_Int(REGB0)<UNTAG_Int(REGB1));
      } else {
        /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
        REGB2 = TAG_Bool(false);
        REGB1 = REGB2;
      }
      if (UNTAG_Bool(REGB1)) {
      } else {
        nit_abort("Assert %s  failed", "'index'", LOCATE_array, 245);
      }
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
      fra.me.REG[8] = ATTR_array___Array____items(fra.me.REG[8]);
      REGB1 = TAG_Bool(fra.me.REG[8]==NIT_NULL);
      if (UNTAG_Bool(REGB1)) {
        nit_abort("Reciever is null", NULL, LOCATE_array, 246);
      }
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:654 */
      fra.me.REG[8] = ((Nit_NativeArray)fra.me.REG[8])->val[UNTAG_Int(REGB0)];
      /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
      goto label13;
      label13: while(0);
      /* ./factory.nit:19 */
      CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[8]);
      fra.me.REG[7] = NEW_Segment_figure___Segment___init(fra.me.REG[7]);
      /* ./factory.nit:22 */
      fra.me.REG[8] = CALL_figure___Segment___taille(fra.me.REG[2])(fra.me.REG[2]);
      fra.me.REG[4] = CALL_figure___Segment___taille(fra.me.REG[4])(fra.me.REG[4]);
      REGB0 = TAG_Bool(IS_EQUAL_OO(fra.me.REG[8],fra.me.REG[4]));
      if (UNTAG_Bool(REGB0)) {
      } else {
        REGB1 = CALL_kernel___Object_____eqeq(fra.me.REG[8])(fra.me.REG[8], fra.me.REG[4]);
        REGB0 = REGB1;
      }
      if (UNTAG_Bool(REGB0)) {
        fra.me.REG[4] = CALL_figure___Segment___taille(fra.me.REG[3])(fra.me.REG[3]);
        fra.me.REG[5] = CALL_figure___Segment___taille(fra.me.REG[5])(fra.me.REG[5]);
        REGB0 = TAG_Bool(IS_EQUAL_OO(fra.me.REG[4],fra.me.REG[5]));
        if (UNTAG_Bool(REGB0)) {
        } else {
          REGB1 = CALL_kernel___Object_____eqeq(fra.me.REG[4])(fra.me.REG[4], fra.me.REG[5]);
          REGB0 = REGB1;
        }
      } else {
        REGB1 = TAG_Bool(false);
        REGB0 = REGB1;
      }
      if (UNTAG_Bool(REGB0)) {
        /* ./factory.nit:25 */
        fra.me.REG[2] = CALL_figure___Segment___taille(fra.me.REG[2])(fra.me.REG[2]);
        fra.me.REG[3] = CALL_figure___Segment___taille(fra.me.REG[3])(fra.me.REG[3]);
        REGB0 = TAG_Bool(IS_EQUAL_OO(fra.me.REG[2],fra.me.REG[3]));
        if (UNTAG_Bool(REGB0)) {
        } else {
          REGB1 = CALL_kernel___Object_____eqeq(fra.me.REG[2])(fra.me.REG[2], fra.me.REG[3]);
          REGB0 = REGB1;
        }
        if (UNTAG_Bool(REGB0)) {
          /* ./factory.nit:28 */
          fra.me.REG[3] = CALL_figure___Segment___taille(fra.me.REG[6])(fra.me.REG[6]);
          fra.me.REG[2] = CALL_figure___Segment___taille(fra.me.REG[7])(fra.me.REG[7]);
          REGB0 = TAG_Bool(IS_EQUAL_OO(fra.me.REG[3],fra.me.REG[2]));
          if (UNTAG_Bool(REGB0)) {
          } else {
            REGB1 = CALL_kernel___Object_____eqeq(fra.me.REG[3])(fra.me.REG[3], fra.me.REG[2]);
            REGB0 = REGB1;
          }
          if (UNTAG_Bool(REGB0)) {
            /* ./factory.nit:29 */
            fra.me.REG[2] = NEW_Carre_polygone___Carre___init(fra.me.REG[1]);
            fra.me.REG[0] = fra.me.REG[2];
            goto label1;
          } else {
            /* ./factory.nit:32 */
            fra.me.REG[2] = NEW_Losange_polygone___Losange___init(fra.me.REG[1]);
            fra.me.REG[0] = fra.me.REG[2];
            goto label1;
          }
        } else {
          /* ./factory.nit:36 */
          fra.me.REG[6] = CALL_figure___Segment___taille(fra.me.REG[6])(fra.me.REG[6]);
          fra.me.REG[7] = CALL_figure___Segment___taille(fra.me.REG[7])(fra.me.REG[7]);
          REGB0 = TAG_Bool(IS_EQUAL_OO(fra.me.REG[6],fra.me.REG[7]));
          if (UNTAG_Bool(REGB0)) {
          } else {
            REGB1 = CALL_kernel___Object_____eqeq(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[7]);
            REGB0 = REGB1;
          }
          if (UNTAG_Bool(REGB0)) {
            /* ./factory.nit:37 */
            fra.me.REG[7] = NEW_Rectangle_polygone___Rectangle___init(fra.me.REG[1]);
            fra.me.REG[0] = fra.me.REG[7];
            goto label1;
          } else {
            /* ./factory.nit:40 */
            fra.me.REG[7] = NEW_Parallelogramme_polygone___Parallelogramme___init(fra.me.REG[1]);
            fra.me.REG[0] = fra.me.REG[7];
            goto label1;
          }
        }
      } else {
        /* ./factory.nit:45 */
        fra.me.REG[7] = NEW_Quadrilatere_polygone___Quadrilatere___init(fra.me.REG[1]);
        fra.me.REG[0] = fra.me.REG[7];
        goto label1;
      }
    } else {
      /* ./factory.nit:50 */
      fra.me.REG[1] = NEW_Polygone_polygone___Polygone___init(fra.me.REG[1]);
      fra.me.REG[0] = fra.me.REG[1];
      goto label1;
    }
  }
  label1: while(0);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[0];
}
void factory___Fabrique___init(val_t p0, int* init_table){
  int itpos0 = VAL2OBJ(p0)->vft[INIT_TABLE_POS_Fabrique].i;
  struct {struct stack_frame_t me;} fra;
  val_t tmp;
  if (init_table[itpos0]) return;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_factory;
  fra.me.line = 0;
  fra.me.meth = LOCATE_factory___Fabrique___init;
  fra.me.has_broke = 0;
  fra.me.REG_size = 0;
  stack_frame_head = fra.me.prev;
  init_table[itpos0] = 1;
  return;
}
