/* This C file is generated by NIT to compile module figure. */
#include "figure._sep.h"
val_t figure___Figure___aire(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_figure;
  fra.me.line = 5;
  fra.me.meth = LOCATE_figure___Figure___aire;
  fra.me.has_broke = 0;
  fra.me.REG_size = 0;
  /* ./figure.nit:5 */
  nit_abort("Deferred method called", NULL, LOCATE_figure, 5);
  stack_frame_head = fra.me.prev;
  return NIT_NULL;
}
val_t figure___Figure___perimetre(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_figure;
  fra.me.line = 7;
  fra.me.meth = LOCATE_figure___Figure___perimetre;
  fra.me.has_broke = 0;
  fra.me.REG_size = 0;
  /* ./figure.nit:7 */
  nit_abort("Deferred method called", NULL, LOCATE_figure, 7);
  stack_frame_head = fra.me.prev;
  return NIT_NULL;
}
val_t figure___Point___x(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_figure;
  fra.me.line = 14;
  fra.me.meth = LOCATE_figure___Point___x;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./figure.nit:14 */
  REGB0 = TAG_Bool(ATTR_figure___Point____x(fra.me.REG[0])!=NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_x", LOCATE_figure, 14);
  }
  fra.me.REG[0] = ATTR_figure___Point____x(fra.me.REG[0]);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[0];
}
val_t figure___Point___y(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_figure;
  fra.me.line = 17;
  fra.me.meth = LOCATE_figure___Point___y;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./figure.nit:17 */
  REGB0 = TAG_Bool(ATTR_figure___Point____y(fra.me.REG[0])!=NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_y", LOCATE_figure, 17);
  }
  fra.me.REG[0] = ATTR_figure___Point____y(fra.me.REG[0]);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[0];
}
void figure___Point___init(val_t p0, val_t p1, val_t p2, int* init_table){
  int itpos0 = VAL2OBJ(p0)->vft[INIT_TABLE_POS_Point].i;
  struct {struct stack_frame_t me; val_t MORE_REG[2];} fra;
  val_t tmp;
  if (init_table[itpos0]) return;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_figure;
  fra.me.line = 20;
  fra.me.meth = LOCATE_figure___Point___init;
  fra.me.has_broke = 0;
  fra.me.REG_size = 3;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[0] = p0;
  fra.me.REG[1] = p1;
  fra.me.REG[2] = p2;
  /* ./figure.nit:23 */
  ATTR_figure___Point____x(fra.me.REG[0]) = fra.me.REG[1];
  /* ./figure.nit:24 */
  ATTR_figure___Point____y(fra.me.REG[0]) = fra.me.REG[2];
  stack_frame_head = fra.me.prev;
  init_table[itpos0] = 1;
  return;
}
val_t figure___Point___aire(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_figure;
  fra.me.line = 27;
  fra.me.meth = LOCATE_figure___Point___aire;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./figure.nit:30 */
  fra.me.REG[0] = BOX_Float(0.0);
  goto label1;
  label1: while(0);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[0];
}
val_t figure___Point___perimetre(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_figure;
  fra.me.line = 33;
  fra.me.meth = LOCATE_figure___Point___perimetre;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./figure.nit:36 */
  fra.me.REG[0] = BOX_Float(0.0);
  goto label1;
  label1: while(0);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[0];
}
val_t figure___Point_____eqeq(val_t p0, val_t p1){
  struct {struct stack_frame_t me; val_t MORE_REG[3];} fra;
  val_t REGB0;
  val_t REGB1;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_figure;
  fra.me.line = 39;
  fra.me.meth = LOCATE_figure___Point_____eqeq;
  fra.me.has_broke = 0;
  fra.me.REG_size = 4;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[3] = NIT_NULL;
  fra.me.REG[0] = p0;
  fra.me.REG[1] = p1;
  /* ./figure.nit:42 */
  REGB0 = TAG_Bool((fra.me.REG[1]!=NIT_NULL) && VAL_ISA(fra.me.REG[1], COLOR_Point, ID_Point)) /*cast Point*/;
  if (UNTAG_Bool(REGB0)) {
    fra.me.REG[2] = CALL_figure___Point___x(fra.me.REG[0])(fra.me.REG[0]);
    REGB0 = TAG_Bool(fra.me.REG[1]==NIT_NULL);
    if (UNTAG_Bool(REGB0)) {
      nit_abort("Reciever is null", NULL, LOCATE_figure, 42);
    }
    fra.me.REG[3] = CALL_figure___Point___x(fra.me.REG[1])(fra.me.REG[1]);
    REGB0 = TAG_Bool(IS_EQUAL_OO(fra.me.REG[2],fra.me.REG[3]));
    if (UNTAG_Bool(REGB0)) {
    } else {
      REGB1 = CALL_kernel___Object_____eqeq(fra.me.REG[2])(fra.me.REG[2], fra.me.REG[3]);
      REGB0 = REGB1;
    }
  } else {
    REGB1 = TAG_Bool(false);
    REGB0 = REGB1;
  }
  if (UNTAG_Bool(REGB0)) {
    fra.me.REG[0] = CALL_figure___Point___y(fra.me.REG[0])(fra.me.REG[0]);
    REGB0 = TAG_Bool(fra.me.REG[1]==NIT_NULL);
    if (UNTAG_Bool(REGB0)) {
      nit_abort("Reciever is null", NULL, LOCATE_figure, 42);
    }
    fra.me.REG[1] = CALL_figure___Point___y(fra.me.REG[1])(fra.me.REG[1]);
    REGB0 = TAG_Bool(IS_EQUAL_OO(fra.me.REG[0],fra.me.REG[1]));
    if (UNTAG_Bool(REGB0)) {
    } else {
      REGB1 = CALL_kernel___Object_____eqeq(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[1]);
      REGB0 = REGB1;
    }
  } else {
    REGB1 = TAG_Bool(false);
    REGB0 = REGB1;
  }
  goto label1;
  label1: while(0);
  stack_frame_head = fra.me.prev;
  return REGB0;
}
val_t figure___Point___to_s(val_t p0){
  struct {struct stack_frame_t me; val_t MORE_REG[2];} fra;
  val_t REGB0;
  val_t tmp;
  static val_t once_value_1; /* Once value */
  static val_t once_value_2; /* Once value */
  static val_t once_value_3; /* Once value */
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_figure;
  fra.me.line = 45;
  fra.me.meth = LOCATE_figure___Point___to_s;
  fra.me.has_broke = 0;
  fra.me.REG_size = 3;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./figure.nit:48 */
  REGB0 = TAG_Int(5);
  fra.me.REG[1] = NEW_Array_array___Array___with_capacity(REGB0);
  if (!once_value_1) {
    fra.me.REG[2] = BOX_NativeString("Point -> x: ");
    REGB0 = TAG_Int(12);
    fra.me.REG[2] = NEW_String_string___String___with_native(fra.me.REG[2], REGB0);
    once_value_1 = fra.me.REG[2];
    register_static_object(&once_value_1);
  } else fra.me.REG[2] = once_value_1;
  fra.me.REG[2] = fra.me.REG[2];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[2]);
  fra.me.REG[2] = CALL_figure___Point___x(fra.me.REG[0])(fra.me.REG[0]);
  fra.me.REG[2] = CALL_string___Object___to_s(fra.me.REG[2])(fra.me.REG[2]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[2]);
  if (!once_value_2) {
    fra.me.REG[2] = BOX_NativeString(", y: ");
    REGB0 = TAG_Int(5);
    fra.me.REG[2] = NEW_String_string___String___with_native(fra.me.REG[2], REGB0);
    once_value_2 = fra.me.REG[2];
    register_static_object(&once_value_2);
  } else fra.me.REG[2] = once_value_2;
  fra.me.REG[2] = fra.me.REG[2];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[2]);
  fra.me.REG[0] = CALL_figure___Point___y(fra.me.REG[0])(fra.me.REG[0]);
  fra.me.REG[0] = CALL_string___Object___to_s(fra.me.REG[0])(fra.me.REG[0]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[0]);
  if (!once_value_3) {
    fra.me.REG[0] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[0] = NEW_String_string___String___with_native(fra.me.REG[0], REGB0);
    once_value_3 = fra.me.REG[0];
    register_static_object(&once_value_3);
  } else fra.me.REG[0] = once_value_3;
  fra.me.REG[0] = fra.me.REG[0];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[0]);
  fra.me.REG[1] = CALL_string___Object___to_s(fra.me.REG[1])(fra.me.REG[1]);
  goto label4;
  label4: while(0);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[1];
}
val_t figure___Segment___sommets(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_figure;
  fra.me.line = 56;
  fra.me.meth = LOCATE_figure___Segment___sommets;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./figure.nit:56 */
  REGB0 = TAG_Bool(ATTR_figure___Segment____sommets(fra.me.REG[0])!=NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_sommets", LOCATE_figure, 56);
  }
  fra.me.REG[0] = ATTR_figure___Segment____sommets(fra.me.REG[0]);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[0];
}
void figure___Segment___init(val_t p0, val_t p1, int* init_table){
  int itpos1 = VAL2OBJ(p0)->vft[INIT_TABLE_POS_Segment].i;
  struct {struct stack_frame_t me; val_t MORE_REG[3];} fra;
  val_t REGB0;
  val_t REGB1;
  val_t REGB2;
  val_t tmp;
    static val_t once_value_1; /* Once value */
    static val_t once_value_4; /* Once value */
  if (init_table[itpos1]) return;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_figure;
  fra.me.line = 59;
  fra.me.meth = LOCATE_figure___Segment___init;
  fra.me.has_broke = 0;
  fra.me.REG_size = 4;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[3] = NIT_NULL;
  fra.me.REG[0] = p0;
  fra.me.REG[1] = p1;
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:23 */
  REGB0 = TAG_Bool(ATTR_array___AbstractArrayRead____length(fra.me.REG[1])!=NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_length", LOCATE_array, 23);
  }
  REGB0 = ATTR_array___AbstractArrayRead____length(fra.me.REG[1]);
  /* ./figure.nit:62 */
  REGB1 = TAG_Int(2);
  REGB2 = TAG_Bool(IS_EQUAL_OO(REGB0,REGB1));
  if (UNTAG_Bool(REGB2)) {
  } else {
    /* /Users/tony/Projects/nit/lib/standard//kernel.nit:207 */
    REGB1 = TAG_Bool((REGB0)==(REGB1));
    /* ./figure.nit:62 */
    REGB2 = REGB1;
  }
  if (UNTAG_Bool(REGB2)) {
  } else {
    /* ./figure.nit:63 */
    if (!once_value_1) {
      fra.me.REG[2] = BOX_NativeString("Un segment doit se composer de deux points.");
      REGB2 = TAG_Int(43);
      fra.me.REG[2] = NEW_String_string___String___with_native(fra.me.REG[2], REGB2);
      once_value_1 = fra.me.REG[2];
      register_static_object(&once_value_1);
    } else fra.me.REG[2] = once_value_1;
    fra.me.REG[2] = fra.me.REG[2];
    CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[2]);
    /* ./figure.nit:62 */
    nit_abort("Assert failed", NULL, LOCATE_figure, 62);
  }
  /* ./figure.nit:65 */
  REGB2 = TAG_Int(0);
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:243 */
  fra.me.REG[2] = fra.me.REG[1];
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
  REGB1 = TAG_Int(0);
  /* /Users/tony/Projects/nit/lib/standard//kernel.nit:213 */
  REGB1 = TAG_Bool(UNTAG_Int(REGB2)>=UNTAG_Int(REGB1));
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
  if (UNTAG_Bool(REGB1)) {
    REGB1 = TAG_Bool(ATTR_array___AbstractArrayRead____length(fra.me.REG[2])!=NIT_NULL);
    if (UNTAG_Bool(REGB1)) {
    } else {
      nit_abort("Uninitialized attribute %s", "_length", LOCATE_array, 245);
    }
    REGB1 = ATTR_array___AbstractArrayRead____length(fra.me.REG[2]);
    /* /Users/tony/Projects/nit/lib/standard//kernel.nit:212 */
    REGB1 = TAG_Bool(UNTAG_Int(REGB2)<UNTAG_Int(REGB1));
  } else {
    /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
    REGB0 = TAG_Bool(false);
    REGB1 = REGB0;
  }
  if (UNTAG_Bool(REGB1)) {
  } else {
    nit_abort("Assert %s  failed", "'index'", LOCATE_array, 245);
  }
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
  fra.me.REG[2] = ATTR_array___Array____items(fra.me.REG[2]);
  REGB1 = TAG_Bool(fra.me.REG[2]==NIT_NULL);
  if (UNTAG_Bool(REGB1)) {
    nit_abort("Reciever is null", NULL, LOCATE_array, 246);
  }
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:654 */
  fra.me.REG[2] = ((Nit_NativeArray)fra.me.REG[2])->val[UNTAG_Int(REGB2)];
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
  goto label2;
  label2: while(0);
  /* ./figure.nit:65 */
  REGB2 = TAG_Int(1);
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:243 */
  fra.me.REG[3] = fra.me.REG[1];
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
  REGB1 = TAG_Int(0);
  /* /Users/tony/Projects/nit/lib/standard//kernel.nit:213 */
  REGB1 = TAG_Bool(UNTAG_Int(REGB2)>=UNTAG_Int(REGB1));
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
  if (UNTAG_Bool(REGB1)) {
    REGB1 = TAG_Bool(ATTR_array___AbstractArrayRead____length(fra.me.REG[3])!=NIT_NULL);
    if (UNTAG_Bool(REGB1)) {
    } else {
      nit_abort("Uninitialized attribute %s", "_length", LOCATE_array, 245);
    }
    REGB1 = ATTR_array___AbstractArrayRead____length(fra.me.REG[3]);
    /* /Users/tony/Projects/nit/lib/standard//kernel.nit:212 */
    REGB1 = TAG_Bool(UNTAG_Int(REGB2)<UNTAG_Int(REGB1));
  } else {
    /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
    REGB0 = TAG_Bool(false);
    REGB1 = REGB0;
  }
  if (UNTAG_Bool(REGB1)) {
  } else {
    nit_abort("Assert %s  failed", "'index'", LOCATE_array, 245);
  }
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
  fra.me.REG[3] = ATTR_array___Array____items(fra.me.REG[3]);
  REGB1 = TAG_Bool(fra.me.REG[3]==NIT_NULL);
  if (UNTAG_Bool(REGB1)) {
    nit_abort("Reciever is null", NULL, LOCATE_array, 246);
  }
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:654 */
  fra.me.REG[3] = ((Nit_NativeArray)fra.me.REG[3])->val[UNTAG_Int(REGB2)];
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
  goto label3;
  label3: while(0);
  /* ./figure.nit:65 */
  REGB2 = TAG_Bool(IS_EQUAL_NN(fra.me.REG[2],fra.me.REG[3]));
  if (UNTAG_Bool(REGB2)) {
  } else {
    REGB1 = TAG_Bool(fra.me.REG[2]==NIT_NULL);
    if (UNTAG_Bool(REGB1)) {
      REGB1 = TAG_Bool(false);
      REGB2 = REGB1;
    } else {
      REGB1 = CALL_kernel___Object_____eqeq(fra.me.REG[2])(fra.me.REG[2], fra.me.REG[3]);
      REGB2 = REGB1;
    }
  }
  REGB2 = TAG_Bool(!UNTAG_Bool(REGB2));
  if (UNTAG_Bool(REGB2)) {
  } else {
    /* ./figure.nit:66 */
    if (!once_value_4) {
      fra.me.REG[3] = BOX_NativeString("Les deux points d'un segment doivent être distincts.");
      REGB2 = TAG_Int(53);
      fra.me.REG[3] = NEW_String_string___String___with_native(fra.me.REG[3], REGB2);
      once_value_4 = fra.me.REG[3];
      register_static_object(&once_value_4);
    } else fra.me.REG[3] = once_value_4;
    fra.me.REG[3] = fra.me.REG[3];
    CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[3]);
    /* ./figure.nit:65 */
    nit_abort("Assert failed", NULL, LOCATE_figure, 65);
  }
  /* ./figure.nit:68 */
  ATTR_figure___Segment____sommets(fra.me.REG[0]) = fra.me.REG[1];
  stack_frame_head = fra.me.prev;
  init_table[itpos1] = 1;
  return;
}
val_t figure___Segment___aire(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_figure;
  fra.me.line = 71;
  fra.me.meth = LOCATE_figure___Segment___aire;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./figure.nit:74 */
  fra.me.REG[0] = BOX_Float(0.0);
  goto label1;
  label1: while(0);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[0];
}
val_t figure___Segment___perimetre(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_figure;
  fra.me.line = 77;
  fra.me.meth = LOCATE_figure___Segment___perimetre;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./figure.nit:80 */
  fra.me.REG[0] = CALL_figure___Segment___taille(fra.me.REG[0])(fra.me.REG[0]);
  goto label1;
  label1: while(0);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[0];
}
val_t figure___Segment_____eqeq(val_t p0, val_t p1){
  struct {struct stack_frame_t me; val_t MORE_REG[1];} fra;
  val_t REGB0;
  val_t REGB1;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_figure;
  fra.me.line = 83;
  fra.me.meth = LOCATE_figure___Segment_____eqeq;
  fra.me.has_broke = 0;
  fra.me.REG_size = 2;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[0] = p0;
  fra.me.REG[1] = p1;
  /* ./figure.nit:86 */
  REGB0 = TAG_Bool((fra.me.REG[1]!=NIT_NULL) && VAL_ISA(fra.me.REG[1], COLOR_Segment, ID_Segment)) /*cast Segment*/;
  if (UNTAG_Bool(REGB0)) {
    REGB0 = TAG_Bool((fra.me.REG[1]!=NIT_NULL) && VAL_ISA(fra.me.REG[1], COLOR_Segment, ID_Segment)) /*cast Segment*/;
    if (UNTAG_Bool(REGB0)) {
    } else {
      nit_abort("Cast failed", NULL, LOCATE_figure, 86);
    }
    REGB0 = TAG_Bool(fra.me.REG[1]==NIT_NULL);
    if (UNTAG_Bool(REGB0)) {
      nit_abort("Reciever is null", NULL, LOCATE_figure, 86);
    }
    fra.me.REG[1] = CALL_figure___Segment___sommets(fra.me.REG[1])(fra.me.REG[1]);
    fra.me.REG[0] = CALL_figure___Segment___sommets(fra.me.REG[0])(fra.me.REG[0]);
    REGB0 = TAG_Bool(IS_EQUAL_OO(fra.me.REG[1],fra.me.REG[0]));
    if (UNTAG_Bool(REGB0)) {
    } else {
      REGB1 = CALL_kernel___Object_____eqeq(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[0]);
      REGB0 = REGB1;
    }
  } else {
    REGB1 = TAG_Bool(false);
    REGB0 = REGB1;
  }
  goto label1;
  label1: while(0);
  stack_frame_head = fra.me.prev;
  return REGB0;
}
val_t figure___Segment___taille(val_t p0){
  struct {struct stack_frame_t me; val_t MORE_REG[2];} fra;
  val_t REGB0;
  val_t REGB1;
  val_t REGB2;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_figure;
  fra.me.line = 89;
  fra.me.meth = LOCATE_figure___Segment___taille;
  fra.me.has_broke = 0;
  fra.me.REG_size = 3;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./figure.nit:92 */
  fra.me.REG[1] = CALL_figure___Segment___sommets(fra.me.REG[0])(fra.me.REG[0]);
  REGB0 = TAG_Int(0);
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
  REGB1 = TAG_Int(0);
  /* /Users/tony/Projects/nit/lib/standard//kernel.nit:213 */
  REGB1 = TAG_Bool(UNTAG_Int(REGB0)>=UNTAG_Int(REGB1));
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
  if (UNTAG_Bool(REGB1)) {
    REGB1 = TAG_Bool(ATTR_array___AbstractArrayRead____length(fra.me.REG[1])!=NIT_NULL);
    if (UNTAG_Bool(REGB1)) {
    } else {
      nit_abort("Uninitialized attribute %s", "_length", LOCATE_array, 245);
    }
    REGB1 = ATTR_array___AbstractArrayRead____length(fra.me.REG[1]);
    /* /Users/tony/Projects/nit/lib/standard//kernel.nit:212 */
    REGB1 = TAG_Bool(UNTAG_Int(REGB0)<UNTAG_Int(REGB1));
  } else {
    /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
    REGB2 = TAG_Bool(false);
    REGB1 = REGB2;
  }
  if (UNTAG_Bool(REGB1)) {
  } else {
    nit_abort("Assert %s  failed", "'index'", LOCATE_array, 245);
  }
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
  fra.me.REG[1] = ATTR_array___Array____items(fra.me.REG[1]);
  REGB1 = TAG_Bool(fra.me.REG[1]==NIT_NULL);
  if (UNTAG_Bool(REGB1)) {
    nit_abort("Reciever is null", NULL, LOCATE_array, 246);
  }
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:654 */
  fra.me.REG[1] = ((Nit_NativeArray)fra.me.REG[1])->val[UNTAG_Int(REGB0)];
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
  goto label1;
  label1: while(0);
  /* ./figure.nit:92 */
  REGB0 = TAG_Bool(fra.me.REG[1]==NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
    nit_abort("Reciever is null", NULL, LOCATE_figure, 92);
  }
  fra.me.REG[1] = CALL_figure___Point___x(fra.me.REG[1])(fra.me.REG[1]);
  fra.me.REG[2] = CALL_figure___Segment___sommets(fra.me.REG[0])(fra.me.REG[0]);
  REGB0 = TAG_Int(1);
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
  REGB1 = TAG_Int(0);
  /* /Users/tony/Projects/nit/lib/standard//kernel.nit:213 */
  REGB1 = TAG_Bool(UNTAG_Int(REGB0)>=UNTAG_Int(REGB1));
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
  if (UNTAG_Bool(REGB1)) {
    REGB1 = TAG_Bool(ATTR_array___AbstractArrayRead____length(fra.me.REG[2])!=NIT_NULL);
    if (UNTAG_Bool(REGB1)) {
    } else {
      nit_abort("Uninitialized attribute %s", "_length", LOCATE_array, 245);
    }
    REGB1 = ATTR_array___AbstractArrayRead____length(fra.me.REG[2]);
    /* /Users/tony/Projects/nit/lib/standard//kernel.nit:212 */
    REGB1 = TAG_Bool(UNTAG_Int(REGB0)<UNTAG_Int(REGB1));
  } else {
    /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
    REGB2 = TAG_Bool(false);
    REGB1 = REGB2;
  }
  if (UNTAG_Bool(REGB1)) {
  } else {
    nit_abort("Assert %s  failed", "'index'", LOCATE_array, 245);
  }
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
  fra.me.REG[2] = ATTR_array___Array____items(fra.me.REG[2]);
  REGB1 = TAG_Bool(fra.me.REG[2]==NIT_NULL);
  if (UNTAG_Bool(REGB1)) {
    nit_abort("Reciever is null", NULL, LOCATE_array, 246);
  }
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:654 */
  fra.me.REG[2] = ((Nit_NativeArray)fra.me.REG[2])->val[UNTAG_Int(REGB0)];
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
  goto label2;
  label2: while(0);
  /* ./figure.nit:92 */
  REGB0 = TAG_Bool(fra.me.REG[2]==NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
    nit_abort("Reciever is null", NULL, LOCATE_figure, 92);
  }
  fra.me.REG[2] = CALL_figure___Point___x(fra.me.REG[2])(fra.me.REG[2]);
  /* /Users/tony/Projects/nit/lib/standard//kernel.nit:192 */
  fra.me.REG[2] = BOX_Float(UNBOX_Float(fra.me.REG[1])-UNBOX_Float(fra.me.REG[2]));
  /* ./figure.nit:92 */
  fra.me.REG[2] = CALL_utils___Float___absolue(fra.me.REG[2])(fra.me.REG[2]);
  /* ./figure.nit:93 */
  fra.me.REG[1] = CALL_figure___Segment___sommets(fra.me.REG[0])(fra.me.REG[0]);
  REGB0 = TAG_Int(0);
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
  REGB1 = TAG_Int(0);
  /* /Users/tony/Projects/nit/lib/standard//kernel.nit:213 */
  REGB1 = TAG_Bool(UNTAG_Int(REGB0)>=UNTAG_Int(REGB1));
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
  if (UNTAG_Bool(REGB1)) {
    REGB1 = TAG_Bool(ATTR_array___AbstractArrayRead____length(fra.me.REG[1])!=NIT_NULL);
    if (UNTAG_Bool(REGB1)) {
    } else {
      nit_abort("Uninitialized attribute %s", "_length", LOCATE_array, 245);
    }
    REGB1 = ATTR_array___AbstractArrayRead____length(fra.me.REG[1]);
    /* /Users/tony/Projects/nit/lib/standard//kernel.nit:212 */
    REGB1 = TAG_Bool(UNTAG_Int(REGB0)<UNTAG_Int(REGB1));
  } else {
    /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
    REGB2 = TAG_Bool(false);
    REGB1 = REGB2;
  }
  if (UNTAG_Bool(REGB1)) {
  } else {
    nit_abort("Assert %s  failed", "'index'", LOCATE_array, 245);
  }
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
  fra.me.REG[1] = ATTR_array___Array____items(fra.me.REG[1]);
  REGB1 = TAG_Bool(fra.me.REG[1]==NIT_NULL);
  if (UNTAG_Bool(REGB1)) {
    nit_abort("Reciever is null", NULL, LOCATE_array, 246);
  }
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:654 */
  fra.me.REG[1] = ((Nit_NativeArray)fra.me.REG[1])->val[UNTAG_Int(REGB0)];
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
  goto label3;
  label3: while(0);
  /* ./figure.nit:93 */
  REGB0 = TAG_Bool(fra.me.REG[1]==NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
    nit_abort("Reciever is null", NULL, LOCATE_figure, 93);
  }
  fra.me.REG[1] = CALL_figure___Point___y(fra.me.REG[1])(fra.me.REG[1]);
  fra.me.REG[0] = CALL_figure___Segment___sommets(fra.me.REG[0])(fra.me.REG[0]);
  REGB0 = TAG_Int(1);
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
  REGB1 = TAG_Int(0);
  /* /Users/tony/Projects/nit/lib/standard//kernel.nit:213 */
  REGB1 = TAG_Bool(UNTAG_Int(REGB0)>=UNTAG_Int(REGB1));
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
  if (UNTAG_Bool(REGB1)) {
    REGB1 = TAG_Bool(ATTR_array___AbstractArrayRead____length(fra.me.REG[0])!=NIT_NULL);
    if (UNTAG_Bool(REGB1)) {
    } else {
      nit_abort("Uninitialized attribute %s", "_length", LOCATE_array, 245);
    }
    REGB1 = ATTR_array___AbstractArrayRead____length(fra.me.REG[0]);
    /* /Users/tony/Projects/nit/lib/standard//kernel.nit:212 */
    REGB1 = TAG_Bool(UNTAG_Int(REGB0)<UNTAG_Int(REGB1));
  } else {
    /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
    REGB2 = TAG_Bool(false);
    REGB1 = REGB2;
  }
  if (UNTAG_Bool(REGB1)) {
  } else {
    nit_abort("Assert %s  failed", "'index'", LOCATE_array, 245);
  }
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
  fra.me.REG[0] = ATTR_array___Array____items(fra.me.REG[0]);
  REGB1 = TAG_Bool(fra.me.REG[0]==NIT_NULL);
  if (UNTAG_Bool(REGB1)) {
    nit_abort("Reciever is null", NULL, LOCATE_array, 246);
  }
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:654 */
  fra.me.REG[0] = ((Nit_NativeArray)fra.me.REG[0])->val[UNTAG_Int(REGB0)];
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
  goto label4;
  label4: while(0);
  /* ./figure.nit:93 */
  REGB0 = TAG_Bool(fra.me.REG[0]==NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
    nit_abort("Reciever is null", NULL, LOCATE_figure, 93);
  }
  fra.me.REG[0] = CALL_figure___Point___y(fra.me.REG[0])(fra.me.REG[0]);
  /* /Users/tony/Projects/nit/lib/standard//kernel.nit:192 */
  fra.me.REG[0] = BOX_Float(UNBOX_Float(fra.me.REG[1])-UNBOX_Float(fra.me.REG[0]));
  /* ./figure.nit:93 */
  fra.me.REG[0] = CALL_utils___Float___absolue(fra.me.REG[0])(fra.me.REG[0]);
  /* ./figure.nit:94 */
  fra.me.REG[1] = BOX_Float(2.0);
  fra.me.REG[1] = CALL_math___Float___pow(fra.me.REG[2])(fra.me.REG[2], fra.me.REG[1]);
  fra.me.REG[2] = BOX_Float(2.0);
  fra.me.REG[2] = CALL_math___Float___pow(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[2]);
  /* /Users/tony/Projects/nit/lib/standard//kernel.nit:190 */
  fra.me.REG[2] = BOX_Float(UNBOX_Float(fra.me.REG[1])+UNBOX_Float(fra.me.REG[2]));
  /* ./figure.nit:94 */
  fra.me.REG[2] = CALL_math___Float___sqrt(fra.me.REG[2])(fra.me.REG[2]);
  goto label5;
  label5: while(0);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[2];
}
val_t figure___Segment___milieu(val_t p0){
  struct {struct stack_frame_t me; val_t MORE_REG[2];} fra;
  val_t REGB0;
  val_t REGB1;
  val_t REGB2;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_figure;
  fra.me.line = 97;
  fra.me.meth = LOCATE_figure___Segment___milieu;
  fra.me.has_broke = 0;
  fra.me.REG_size = 3;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./figure.nit:100 */
  fra.me.REG[1] = CALL_figure___Segment___sommets(fra.me.REG[0])(fra.me.REG[0]);
  REGB0 = TAG_Int(0);
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
  REGB1 = TAG_Int(0);
  /* /Users/tony/Projects/nit/lib/standard//kernel.nit:213 */
  REGB1 = TAG_Bool(UNTAG_Int(REGB0)>=UNTAG_Int(REGB1));
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
  if (UNTAG_Bool(REGB1)) {
    REGB1 = TAG_Bool(ATTR_array___AbstractArrayRead____length(fra.me.REG[1])!=NIT_NULL);
    if (UNTAG_Bool(REGB1)) {
    } else {
      nit_abort("Uninitialized attribute %s", "_length", LOCATE_array, 245);
    }
    REGB1 = ATTR_array___AbstractArrayRead____length(fra.me.REG[1]);
    /* /Users/tony/Projects/nit/lib/standard//kernel.nit:212 */
    REGB1 = TAG_Bool(UNTAG_Int(REGB0)<UNTAG_Int(REGB1));
  } else {
    /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
    REGB2 = TAG_Bool(false);
    REGB1 = REGB2;
  }
  if (UNTAG_Bool(REGB1)) {
  } else {
    nit_abort("Assert %s  failed", "'index'", LOCATE_array, 245);
  }
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
  fra.me.REG[1] = ATTR_array___Array____items(fra.me.REG[1]);
  REGB1 = TAG_Bool(fra.me.REG[1]==NIT_NULL);
  if (UNTAG_Bool(REGB1)) {
    nit_abort("Reciever is null", NULL, LOCATE_array, 246);
  }
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:654 */
  fra.me.REG[1] = ((Nit_NativeArray)fra.me.REG[1])->val[UNTAG_Int(REGB0)];
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
  goto label1;
  label1: while(0);
  /* ./figure.nit:100 */
  REGB0 = TAG_Bool(fra.me.REG[1]==NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
    nit_abort("Reciever is null", NULL, LOCATE_figure, 100);
  }
  fra.me.REG[1] = CALL_figure___Point___x(fra.me.REG[1])(fra.me.REG[1]);
  fra.me.REG[2] = CALL_figure___Segment___sommets(fra.me.REG[0])(fra.me.REG[0]);
  REGB0 = TAG_Int(1);
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
  REGB1 = TAG_Int(0);
  /* /Users/tony/Projects/nit/lib/standard//kernel.nit:213 */
  REGB1 = TAG_Bool(UNTAG_Int(REGB0)>=UNTAG_Int(REGB1));
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
  if (UNTAG_Bool(REGB1)) {
    REGB1 = TAG_Bool(ATTR_array___AbstractArrayRead____length(fra.me.REG[2])!=NIT_NULL);
    if (UNTAG_Bool(REGB1)) {
    } else {
      nit_abort("Uninitialized attribute %s", "_length", LOCATE_array, 245);
    }
    REGB1 = ATTR_array___AbstractArrayRead____length(fra.me.REG[2]);
    /* /Users/tony/Projects/nit/lib/standard//kernel.nit:212 */
    REGB1 = TAG_Bool(UNTAG_Int(REGB0)<UNTAG_Int(REGB1));
  } else {
    /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
    REGB2 = TAG_Bool(false);
    REGB1 = REGB2;
  }
  if (UNTAG_Bool(REGB1)) {
  } else {
    nit_abort("Assert %s  failed", "'index'", LOCATE_array, 245);
  }
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
  fra.me.REG[2] = ATTR_array___Array____items(fra.me.REG[2]);
  REGB1 = TAG_Bool(fra.me.REG[2]==NIT_NULL);
  if (UNTAG_Bool(REGB1)) {
    nit_abort("Reciever is null", NULL, LOCATE_array, 246);
  }
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:654 */
  fra.me.REG[2] = ((Nit_NativeArray)fra.me.REG[2])->val[UNTAG_Int(REGB0)];
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
  goto label2;
  label2: while(0);
  /* ./figure.nit:100 */
  REGB0 = TAG_Bool(fra.me.REG[2]==NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
    nit_abort("Reciever is null", NULL, LOCATE_figure, 100);
  }
  fra.me.REG[2] = CALL_figure___Point___x(fra.me.REG[2])(fra.me.REG[2]);
  /* /Users/tony/Projects/nit/lib/standard//kernel.nit:190 */
  fra.me.REG[2] = BOX_Float(UNBOX_Float(fra.me.REG[1])+UNBOX_Float(fra.me.REG[2]));
  /* ./figure.nit:100 */
  fra.me.REG[1] = BOX_Float(2.0);
  /* /Users/tony/Projects/nit/lib/standard//kernel.nit:194 */
  fra.me.REG[1] = BOX_Float(UNBOX_Float(fra.me.REG[2])/UNBOX_Float(fra.me.REG[1]));
  /* ./figure.nit:101 */
  fra.me.REG[2] = CALL_figure___Segment___sommets(fra.me.REG[0])(fra.me.REG[0]);
  REGB0 = TAG_Int(0);
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
  REGB1 = TAG_Int(0);
  /* /Users/tony/Projects/nit/lib/standard//kernel.nit:213 */
  REGB1 = TAG_Bool(UNTAG_Int(REGB0)>=UNTAG_Int(REGB1));
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
  if (UNTAG_Bool(REGB1)) {
    REGB1 = TAG_Bool(ATTR_array___AbstractArrayRead____length(fra.me.REG[2])!=NIT_NULL);
    if (UNTAG_Bool(REGB1)) {
    } else {
      nit_abort("Uninitialized attribute %s", "_length", LOCATE_array, 245);
    }
    REGB1 = ATTR_array___AbstractArrayRead____length(fra.me.REG[2]);
    /* /Users/tony/Projects/nit/lib/standard//kernel.nit:212 */
    REGB1 = TAG_Bool(UNTAG_Int(REGB0)<UNTAG_Int(REGB1));
  } else {
    /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
    REGB2 = TAG_Bool(false);
    REGB1 = REGB2;
  }
  if (UNTAG_Bool(REGB1)) {
  } else {
    nit_abort("Assert %s  failed", "'index'", LOCATE_array, 245);
  }
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
  fra.me.REG[2] = ATTR_array___Array____items(fra.me.REG[2]);
  REGB1 = TAG_Bool(fra.me.REG[2]==NIT_NULL);
  if (UNTAG_Bool(REGB1)) {
    nit_abort("Reciever is null", NULL, LOCATE_array, 246);
  }
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:654 */
  fra.me.REG[2] = ((Nit_NativeArray)fra.me.REG[2])->val[UNTAG_Int(REGB0)];
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
  goto label3;
  label3: while(0);
  /* ./figure.nit:101 */
  REGB0 = TAG_Bool(fra.me.REG[2]==NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
    nit_abort("Reciever is null", NULL, LOCATE_figure, 101);
  }
  fra.me.REG[2] = CALL_figure___Point___y(fra.me.REG[2])(fra.me.REG[2]);
  fra.me.REG[0] = CALL_figure___Segment___sommets(fra.me.REG[0])(fra.me.REG[0]);
  REGB0 = TAG_Int(1);
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
  REGB1 = TAG_Int(0);
  /* /Users/tony/Projects/nit/lib/standard//kernel.nit:213 */
  REGB1 = TAG_Bool(UNTAG_Int(REGB0)>=UNTAG_Int(REGB1));
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
  if (UNTAG_Bool(REGB1)) {
    REGB1 = TAG_Bool(ATTR_array___AbstractArrayRead____length(fra.me.REG[0])!=NIT_NULL);
    if (UNTAG_Bool(REGB1)) {
    } else {
      nit_abort("Uninitialized attribute %s", "_length", LOCATE_array, 245);
    }
    REGB1 = ATTR_array___AbstractArrayRead____length(fra.me.REG[0]);
    /* /Users/tony/Projects/nit/lib/standard//kernel.nit:212 */
    REGB1 = TAG_Bool(UNTAG_Int(REGB0)<UNTAG_Int(REGB1));
  } else {
    /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
    REGB2 = TAG_Bool(false);
    REGB1 = REGB2;
  }
  if (UNTAG_Bool(REGB1)) {
  } else {
    nit_abort("Assert %s  failed", "'index'", LOCATE_array, 245);
  }
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
  fra.me.REG[0] = ATTR_array___Array____items(fra.me.REG[0]);
  REGB1 = TAG_Bool(fra.me.REG[0]==NIT_NULL);
  if (UNTAG_Bool(REGB1)) {
    nit_abort("Reciever is null", NULL, LOCATE_array, 246);
  }
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:654 */
  fra.me.REG[0] = ((Nit_NativeArray)fra.me.REG[0])->val[UNTAG_Int(REGB0)];
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
  goto label4;
  label4: while(0);
  /* ./figure.nit:101 */
  REGB0 = TAG_Bool(fra.me.REG[0]==NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
    nit_abort("Reciever is null", NULL, LOCATE_figure, 101);
  }
  fra.me.REG[0] = CALL_figure___Point___y(fra.me.REG[0])(fra.me.REG[0]);
  /* /Users/tony/Projects/nit/lib/standard//kernel.nit:190 */
  fra.me.REG[0] = BOX_Float(UNBOX_Float(fra.me.REG[2])+UNBOX_Float(fra.me.REG[0]));
  /* ./figure.nit:101 */
  fra.me.REG[2] = BOX_Float(2.0);
  /* /Users/tony/Projects/nit/lib/standard//kernel.nit:194 */
  fra.me.REG[2] = BOX_Float(UNBOX_Float(fra.me.REG[0])/UNBOX_Float(fra.me.REG[2]));
  /* ./figure.nit:102 */
  fra.me.REG[2] = NEW_Point_figure___Point___init(fra.me.REG[1], fra.me.REG[2]);
  goto label5;
  label5: while(0);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[2];
}
val_t figure___Segment___to_s(val_t p0){
  struct {struct stack_frame_t me; val_t MORE_REG[2];} fra;
  val_t REGB0;
  val_t REGB1;
  val_t REGB2;
  val_t tmp;
  static val_t once_value_1; /* Once value */
  static val_t once_value_3; /* Once value */
  static val_t once_value_5; /* Once value */
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_figure;
  fra.me.line = 105;
  fra.me.meth = LOCATE_figure___Segment___to_s;
  fra.me.has_broke = 0;
  fra.me.REG_size = 3;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./figure.nit:108 */
  REGB0 = TAG_Int(5);
  fra.me.REG[1] = NEW_Array_array___Array___with_capacity(REGB0);
  if (!once_value_1) {
    fra.me.REG[2] = BOX_NativeString("Segment -> [");
    REGB0 = TAG_Int(12);
    fra.me.REG[2] = NEW_String_string___String___with_native(fra.me.REG[2], REGB0);
    once_value_1 = fra.me.REG[2];
    register_static_object(&once_value_1);
  } else fra.me.REG[2] = once_value_1;
  fra.me.REG[2] = fra.me.REG[2];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[2]);
  fra.me.REG[2] = CALL_figure___Segment___sommets(fra.me.REG[0])(fra.me.REG[0]);
  REGB0 = TAG_Int(0);
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
  REGB1 = TAG_Int(0);
  /* /Users/tony/Projects/nit/lib/standard//kernel.nit:213 */
  REGB1 = TAG_Bool(UNTAG_Int(REGB0)>=UNTAG_Int(REGB1));
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
  if (UNTAG_Bool(REGB1)) {
    REGB1 = TAG_Bool(ATTR_array___AbstractArrayRead____length(fra.me.REG[2])!=NIT_NULL);
    if (UNTAG_Bool(REGB1)) {
    } else {
      nit_abort("Uninitialized attribute %s", "_length", LOCATE_array, 245);
    }
    REGB1 = ATTR_array___AbstractArrayRead____length(fra.me.REG[2]);
    /* /Users/tony/Projects/nit/lib/standard//kernel.nit:212 */
    REGB1 = TAG_Bool(UNTAG_Int(REGB0)<UNTAG_Int(REGB1));
  } else {
    /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
    REGB2 = TAG_Bool(false);
    REGB1 = REGB2;
  }
  if (UNTAG_Bool(REGB1)) {
  } else {
    nit_abort("Assert %s  failed", "'index'", LOCATE_array, 245);
  }
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
  fra.me.REG[2] = ATTR_array___Array____items(fra.me.REG[2]);
  REGB1 = TAG_Bool(fra.me.REG[2]==NIT_NULL);
  if (UNTAG_Bool(REGB1)) {
    nit_abort("Reciever is null", NULL, LOCATE_array, 246);
  }
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:654 */
  fra.me.REG[2] = ((Nit_NativeArray)fra.me.REG[2])->val[UNTAG_Int(REGB0)];
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
  goto label2;
  label2: while(0);
  /* ./figure.nit:108 */
  fra.me.REG[2] = CALL_string___Object___to_s(fra.me.REG[2])(fra.me.REG[2]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[2]);
  if (!once_value_3) {
    fra.me.REG[2] = BOX_NativeString(",");
    REGB0 = TAG_Int(1);
    fra.me.REG[2] = NEW_String_string___String___with_native(fra.me.REG[2], REGB0);
    once_value_3 = fra.me.REG[2];
    register_static_object(&once_value_3);
  } else fra.me.REG[2] = once_value_3;
  fra.me.REG[2] = fra.me.REG[2];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[2]);
  fra.me.REG[0] = CALL_figure___Segment___sommets(fra.me.REG[0])(fra.me.REG[0]);
  REGB0 = TAG_Int(1);
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
  REGB1 = TAG_Int(0);
  /* /Users/tony/Projects/nit/lib/standard//kernel.nit:213 */
  REGB1 = TAG_Bool(UNTAG_Int(REGB0)>=UNTAG_Int(REGB1));
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
  if (UNTAG_Bool(REGB1)) {
    REGB1 = TAG_Bool(ATTR_array___AbstractArrayRead____length(fra.me.REG[0])!=NIT_NULL);
    if (UNTAG_Bool(REGB1)) {
    } else {
      nit_abort("Uninitialized attribute %s", "_length", LOCATE_array, 245);
    }
    REGB1 = ATTR_array___AbstractArrayRead____length(fra.me.REG[0]);
    /* /Users/tony/Projects/nit/lib/standard//kernel.nit:212 */
    REGB1 = TAG_Bool(UNTAG_Int(REGB0)<UNTAG_Int(REGB1));
  } else {
    /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
    REGB2 = TAG_Bool(false);
    REGB1 = REGB2;
  }
  if (UNTAG_Bool(REGB1)) {
  } else {
    nit_abort("Assert %s  failed", "'index'", LOCATE_array, 245);
  }
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
  fra.me.REG[0] = ATTR_array___Array____items(fra.me.REG[0]);
  REGB1 = TAG_Bool(fra.me.REG[0]==NIT_NULL);
  if (UNTAG_Bool(REGB1)) {
    nit_abort("Reciever is null", NULL, LOCATE_array, 246);
  }
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:654 */
  fra.me.REG[0] = ((Nit_NativeArray)fra.me.REG[0])->val[UNTAG_Int(REGB0)];
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
  goto label4;
  label4: while(0);
  /* ./figure.nit:108 */
  fra.me.REG[0] = CALL_string___Object___to_s(fra.me.REG[0])(fra.me.REG[0]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[0]);
  if (!once_value_5) {
    fra.me.REG[0] = BOX_NativeString("]");
    REGB0 = TAG_Int(1);
    fra.me.REG[0] = NEW_String_string___String___with_native(fra.me.REG[0], REGB0);
    once_value_5 = fra.me.REG[0];
    register_static_object(&once_value_5);
  } else fra.me.REG[0] = once_value_5;
  fra.me.REG[0] = fra.me.REG[0];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[0]);
  fra.me.REG[1] = CALL_string___Object___to_s(fra.me.REG[1])(fra.me.REG[1]);
  goto label6;
  label6: while(0);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[1];
}
val_t figure___Cercle___centre(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_figure;
  fra.me.line = 116;
  fra.me.meth = LOCATE_figure___Cercle___centre;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./figure.nit:116 */
  REGB0 = TAG_Bool(ATTR_figure___Cercle____centre(fra.me.REG[0])!=NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_centre", LOCATE_figure, 116);
  }
  fra.me.REG[0] = ATTR_figure___Cercle____centre(fra.me.REG[0]);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[0];
}
val_t figure___Cercle___rayon(val_t p0){
  struct {struct stack_frame_t me;} fra;
  val_t REGB0;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_figure;
  fra.me.line = 119;
  fra.me.meth = LOCATE_figure___Cercle___rayon;
  fra.me.has_broke = 0;
  fra.me.REG_size = 1;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./figure.nit:119 */
  REGB0 = TAG_Bool(ATTR_figure___Cercle____rayon(fra.me.REG[0])!=NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
  } else {
    nit_abort("Uninitialized attribute %s", "_rayon", LOCATE_figure, 119);
  }
  fra.me.REG[0] = ATTR_figure___Cercle____rayon(fra.me.REG[0]);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[0];
}
void figure___Cercle___init(val_t p0, val_t p1, val_t p2, int* init_table){
  int itpos2 = VAL2OBJ(p0)->vft[INIT_TABLE_POS_Cercle].i;
  struct {struct stack_frame_t me; val_t MORE_REG[2];} fra;
  val_t tmp;
  if (init_table[itpos2]) return;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_figure;
  fra.me.line = 122;
  fra.me.meth = LOCATE_figure___Cercle___init;
  fra.me.has_broke = 0;
  fra.me.REG_size = 3;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[0] = p0;
  fra.me.REG[1] = p1;
  fra.me.REG[2] = p2;
  /* ./figure.nit:125 */
  ATTR_figure___Cercle____centre(fra.me.REG[0]) = fra.me.REG[1];
  /* ./figure.nit:126 */
  ATTR_figure___Cercle____rayon(fra.me.REG[0]) = fra.me.REG[2];
  stack_frame_head = fra.me.prev;
  init_table[itpos2] = 1;
  return;
}
val_t figure___Cercle___aire(val_t p0){
  struct {struct stack_frame_t me; val_t MORE_REG[2];} fra;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_figure;
  fra.me.line = 129;
  fra.me.meth = LOCATE_figure___Cercle___aire;
  fra.me.has_broke = 0;
  fra.me.REG_size = 3;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./figure.nit:132 */
  fra.me.REG[1] = CALL_math___Object___pi(fra.me.REG[0])(fra.me.REG[0]);
  fra.me.REG[0] = CALL_figure___Cercle___rayon(fra.me.REG[0])(fra.me.REG[0]);
  fra.me.REG[2] = BOX_Float(2.0);
  fra.me.REG[2] = CALL_math___Float___pow(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[2]);
  /* /Users/tony/Projects/nit/lib/standard//kernel.nit:193 */
  fra.me.REG[2] = BOX_Float(UNBOX_Float(fra.me.REG[1])*UNBOX_Float(fra.me.REG[2]));
  /* ./figure.nit:132 */
  goto label1;
  label1: while(0);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[2];
}
val_t figure___Cercle___perimetre(val_t p0){
  struct {struct stack_frame_t me; val_t MORE_REG[2];} fra;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_figure;
  fra.me.line = 135;
  fra.me.meth = LOCATE_figure___Cercle___perimetre;
  fra.me.has_broke = 0;
  fra.me.REG_size = 3;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./figure.nit:138 */
  fra.me.REG[1] = BOX_Float(2.0);
  fra.me.REG[2] = CALL_math___Object___pi(fra.me.REG[0])(fra.me.REG[0]);
  /* /Users/tony/Projects/nit/lib/standard//kernel.nit:193 */
  fra.me.REG[2] = BOX_Float(UNBOX_Float(fra.me.REG[1])*UNBOX_Float(fra.me.REG[2]));
  /* ./figure.nit:138 */
  fra.me.REG[0] = CALL_figure___Cercle___rayon(fra.me.REG[0])(fra.me.REG[0]);
  /* /Users/tony/Projects/nit/lib/standard//kernel.nit:193 */
  fra.me.REG[0] = BOX_Float(UNBOX_Float(fra.me.REG[2])*UNBOX_Float(fra.me.REG[0]));
  /* ./figure.nit:138 */
  goto label1;
  label1: while(0);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[0];
}
val_t figure___Cercle_____eqeq(val_t p0, val_t p1){
  struct {struct stack_frame_t me; val_t MORE_REG[3];} fra;
  val_t REGB0;
  val_t REGB1;
  val_t tmp;
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_figure;
  fra.me.line = 141;
  fra.me.meth = LOCATE_figure___Cercle_____eqeq;
  fra.me.has_broke = 0;
  fra.me.REG_size = 4;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[3] = NIT_NULL;
  fra.me.REG[0] = p0;
  fra.me.REG[1] = p1;
  /* ./figure.nit:144 */
  REGB0 = TAG_Bool((fra.me.REG[1]!=NIT_NULL) && VAL_ISA(fra.me.REG[1], COLOR_Cercle, ID_Cercle)) /*cast Cercle*/;
  if (UNTAG_Bool(REGB0)) {
    REGB0 = TAG_Bool((fra.me.REG[1]!=NIT_NULL) && VAL_ISA(fra.me.REG[1], COLOR_Cercle, ID_Cercle)) /*cast Cercle*/;
    if (UNTAG_Bool(REGB0)) {
    } else {
      nit_abort("Cast failed", NULL, LOCATE_figure, 144);
    }
    REGB0 = TAG_Bool(fra.me.REG[1]==NIT_NULL);
    if (UNTAG_Bool(REGB0)) {
      nit_abort("Reciever is null", NULL, LOCATE_figure, 144);
    }
    fra.me.REG[2] = CALL_figure___Cercle___centre(fra.me.REG[1])(fra.me.REG[1]);
    fra.me.REG[3] = CALL_figure___Cercle___centre(fra.me.REG[0])(fra.me.REG[0]);
    REGB0 = TAG_Bool(IS_EQUAL_OO(fra.me.REG[2],fra.me.REG[3]));
    if (UNTAG_Bool(REGB0)) {
    } else {
      REGB1 = CALL_kernel___Object_____eqeq(fra.me.REG[2])(fra.me.REG[2], fra.me.REG[3]);
      REGB0 = REGB1;
    }
  } else {
    REGB1 = TAG_Bool(false);
    REGB0 = REGB1;
  }
  if (UNTAG_Bool(REGB0)) {
    REGB0 = TAG_Bool((fra.me.REG[1]!=NIT_NULL) && VAL_ISA(fra.me.REG[1], COLOR_Cercle, ID_Cercle)) /*cast Cercle*/;
    if (UNTAG_Bool(REGB0)) {
    } else {
      nit_abort("Cast failed", NULL, LOCATE_figure, 144);
    }
    REGB0 = TAG_Bool(fra.me.REG[1]==NIT_NULL);
    if (UNTAG_Bool(REGB0)) {
      nit_abort("Reciever is null", NULL, LOCATE_figure, 144);
    }
    fra.me.REG[1] = CALL_figure___Cercle___rayon(fra.me.REG[1])(fra.me.REG[1]);
    fra.me.REG[0] = CALL_figure___Cercle___rayon(fra.me.REG[0])(fra.me.REG[0]);
    REGB0 = TAG_Bool(IS_EQUAL_OO(fra.me.REG[1],fra.me.REG[0]));
    if (UNTAG_Bool(REGB0)) {
    } else {
      REGB1 = CALL_kernel___Object_____eqeq(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[0]);
      REGB0 = REGB1;
    }
  } else {
    REGB1 = TAG_Bool(false);
    REGB0 = REGB1;
  }
  goto label1;
  label1: while(0);
  stack_frame_head = fra.me.prev;
  return REGB0;
}
val_t figure___Cercle___to_s(val_t p0){
  struct {struct stack_frame_t me; val_t MORE_REG[2];} fra;
  val_t REGB0;
  val_t tmp;
  static val_t once_value_1; /* Once value */
  static val_t once_value_2; /* Once value */
  static val_t once_value_3; /* Once value */
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_figure;
  fra.me.line = 147;
  fra.me.meth = LOCATE_figure___Cercle___to_s;
  fra.me.has_broke = 0;
  fra.me.REG_size = 3;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./figure.nit:150 */
  REGB0 = TAG_Int(5);
  fra.me.REG[1] = NEW_Array_array___Array___with_capacity(REGB0);
  if (!once_value_1) {
    fra.me.REG[2] = BOX_NativeString("Cercle -> rayon: ");
    REGB0 = TAG_Int(17);
    fra.me.REG[2] = NEW_String_string___String___with_native(fra.me.REG[2], REGB0);
    once_value_1 = fra.me.REG[2];
    register_static_object(&once_value_1);
  } else fra.me.REG[2] = once_value_1;
  fra.me.REG[2] = fra.me.REG[2];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[2]);
  fra.me.REG[2] = CALL_figure___Cercle___rayon(fra.me.REG[0])(fra.me.REG[0]);
  fra.me.REG[2] = CALL_string___Object___to_s(fra.me.REG[2])(fra.me.REG[2]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[2]);
  if (!once_value_2) {
    fra.me.REG[2] = BOX_NativeString(", centre: [");
    REGB0 = TAG_Int(11);
    fra.me.REG[2] = NEW_String_string___String___with_native(fra.me.REG[2], REGB0);
    once_value_2 = fra.me.REG[2];
    register_static_object(&once_value_2);
  } else fra.me.REG[2] = once_value_2;
  fra.me.REG[2] = fra.me.REG[2];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[2]);
  fra.me.REG[0] = CALL_figure___Cercle___centre(fra.me.REG[0])(fra.me.REG[0]);
  fra.me.REG[0] = CALL_string___Object___to_s(fra.me.REG[0])(fra.me.REG[0]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[0]);
  if (!once_value_3) {
    fra.me.REG[0] = BOX_NativeString("]");
    REGB0 = TAG_Int(1);
    fra.me.REG[0] = NEW_String_string___String___with_native(fra.me.REG[0], REGB0);
    once_value_3 = fra.me.REG[0];
    register_static_object(&once_value_3);
  } else fra.me.REG[0] = once_value_3;
  fra.me.REG[0] = fra.me.REG[0];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[0]);
  fra.me.REG[1] = CALL_string___Object___to_s(fra.me.REG[1])(fra.me.REG[1]);
  goto label4;
  label4: while(0);
  stack_frame_head = fra.me.prev;
  return fra.me.REG[1];
}
