/* This C file is generated by NIT to compile module main. */
#include "main._sep.h"
void main___Sys___main(val_t p0){
  struct {struct stack_frame_t me; val_t MORE_REG[8];} fra;
  val_t REGB0;
  val_t REGB1;
  val_t tmp;
  static val_t once_value_1; /* Once value */
  static val_t once_value_2; /* Once value */
  static val_t once_value_3; /* Once value */
  static val_t once_value_4; /* Once value */
  static val_t once_value_5; /* Once value */
  static val_t once_value_6; /* Once value */
  static val_t once_value_7; /* Once value */
  static val_t once_value_8; /* Once value */
  static val_t once_value_9; /* Once value */
  static val_t once_value_10; /* Once value */
    static val_t once_value_11; /* Once value */
    static val_t once_value_12; /* Once value */
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_main;
  fra.me.line = 3;
  fra.me.meth = LOCATE_main___Sys___main;
  fra.me.has_broke = 0;
  fra.me.REG_size = 9;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[3] = NIT_NULL;
  fra.me.REG[4] = NIT_NULL;
  fra.me.REG[5] = NIT_NULL;
  fra.me.REG[6] = NIT_NULL;
  fra.me.REG[7] = NIT_NULL;
  fra.me.REG[8] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./main.nit:3 */
  fra.me.REG[1] = BOX_Float(0.0);
  fra.me.REG[2] = BOX_Float(20.0);
  fra.me.REG[2] = NEW_Point_figure___Point___init(fra.me.REG[1], fra.me.REG[2]);
  /* ./main.nit:4 */
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[2]);
  /* ./main.nit:5 */
  fra.me.REG[1] = BOX_Float(0.0);
  fra.me.REG[3] = BOX_Float(10.0);
  /* /Users/tony/Projects/nit/lib/standard//kernel.nit:191 */
  fra.me.REG[3] = BOX_Float(-UNBOX_Float(fra.me.REG[3]));
  /* ./main.nit:5 */
  fra.me.REG[3] = NEW_Point_figure___Point___init(fra.me.REG[1], fra.me.REG[3]);
  /* ./main.nit:6 */
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[3]);
  /* ./main.nit:8 */
  REGB0 = TAG_Int(2);
  fra.me.REG[1] = NEW_Array_array___Array___with_capacity(REGB0);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[2]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[3]);
  fra.me.REG[1] = NEW_Segment_figure___Segment___init(fra.me.REG[1]);
  /* ./main.nit:9 */
  fra.me.REG[3] = CALL_figure___Figure___perimetre(fra.me.REG[1])(fra.me.REG[1]);
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[3]);
  /* ./main.nit:10 */
  REGB0 = TAG_Int(3);
  fra.me.REG[3] = NEW_Array_array___Array___with_capacity(REGB0);
  if (!once_value_1) {
    fra.me.REG[4] = BOX_NativeString("Milieu x: ");
    REGB0 = TAG_Int(10);
    fra.me.REG[4] = NEW_String_string___String___with_native(fra.me.REG[4], REGB0);
    once_value_1 = fra.me.REG[4];
    register_static_object(&once_value_1);
  } else fra.me.REG[4] = once_value_1;
  fra.me.REG[4] = fra.me.REG[4];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[3])(fra.me.REG[3], fra.me.REG[4]);
  fra.me.REG[4] = CALL_figure___Segment___milieu(fra.me.REG[1])(fra.me.REG[1]);
  fra.me.REG[4] = CALL_figure___Point___x(fra.me.REG[4])(fra.me.REG[4]);
  fra.me.REG[4] = CALL_string___Object___to_s(fra.me.REG[4])(fra.me.REG[4]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[3])(fra.me.REG[3], fra.me.REG[4]);
  if (!once_value_2) {
    fra.me.REG[4] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[4] = NEW_String_string___String___with_native(fra.me.REG[4], REGB0);
    once_value_2 = fra.me.REG[4];
    register_static_object(&once_value_2);
  } else fra.me.REG[4] = once_value_2;
  fra.me.REG[4] = fra.me.REG[4];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[3])(fra.me.REG[3], fra.me.REG[4]);
  fra.me.REG[3] = CALL_string___Object___to_s(fra.me.REG[3])(fra.me.REG[3]);
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[3]);
  /* ./main.nit:11 */
  REGB0 = TAG_Int(3);
  fra.me.REG[3] = NEW_Array_array___Array___with_capacity(REGB0);
  if (!once_value_3) {
    fra.me.REG[4] = BOX_NativeString("Milieu y: ");
    REGB0 = TAG_Int(10);
    fra.me.REG[4] = NEW_String_string___String___with_native(fra.me.REG[4], REGB0);
    once_value_3 = fra.me.REG[4];
    register_static_object(&once_value_3);
  } else fra.me.REG[4] = once_value_3;
  fra.me.REG[4] = fra.me.REG[4];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[3])(fra.me.REG[3], fra.me.REG[4]);
  fra.me.REG[1] = CALL_figure___Segment___milieu(fra.me.REG[1])(fra.me.REG[1]);
  fra.me.REG[1] = CALL_figure___Point___y(fra.me.REG[1])(fra.me.REG[1]);
  fra.me.REG[1] = CALL_string___Object___to_s(fra.me.REG[1])(fra.me.REG[1]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[3])(fra.me.REG[3], fra.me.REG[1]);
  if (!once_value_4) {
    fra.me.REG[1] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[1] = NEW_String_string___String___with_native(fra.me.REG[1], REGB0);
    once_value_4 = fra.me.REG[1];
    register_static_object(&once_value_4);
  } else fra.me.REG[1] = once_value_4;
  fra.me.REG[1] = fra.me.REG[1];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[3])(fra.me.REG[3], fra.me.REG[1]);
  fra.me.REG[3] = CALL_string___Object___to_s(fra.me.REG[3])(fra.me.REG[3]);
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[3]);
  /* ./main.nit:13 */
  fra.me.REG[3] = BOX_Float(5.0);
  fra.me.REG[3] = NEW_Cercle_figure___Cercle___init(fra.me.REG[2], fra.me.REG[3]);
  /* ./main.nit:14 */
  fra.me.REG[2] = CALL_figure___Figure___aire(fra.me.REG[3])(fra.me.REG[3]);
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[2]);
  /* ./main.nit:15 */
  fra.me.REG[3] = CALL_figure___Figure___perimetre(fra.me.REG[3])(fra.me.REG[3]);
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[3]);
  /* ./main.nit:17 */
  fra.me.REG[3] = BOX_Float(0.0);
  fra.me.REG[2] = BOX_Float(5.0);
  fra.me.REG[2] = NEW_Point_figure___Point___init(fra.me.REG[3], fra.me.REG[2]);
  /* ./main.nit:18 */
  fra.me.REG[3] = BOX_Float(5.0);
  fra.me.REG[1] = BOX_Float(5.0);
  fra.me.REG[1] = NEW_Point_figure___Point___init(fra.me.REG[3], fra.me.REG[1]);
  /* ./main.nit:19 */
  fra.me.REG[3] = BOX_Float(5.0);
  fra.me.REG[4] = BOX_Float(0.0);
  fra.me.REG[4] = NEW_Point_figure___Point___init(fra.me.REG[3], fra.me.REG[4]);
  /* ./main.nit:20 */
  fra.me.REG[3] = BOX_Float(0.0);
  fra.me.REG[5] = BOX_Float(0.0);
  fra.me.REG[5] = NEW_Point_figure___Point___init(fra.me.REG[3], fra.me.REG[5]);
  /* ./main.nit:21 */
  REGB0 = TAG_Int(4);
  fra.me.REG[3] = NEW_Array_array___Array___with_capacity(REGB0);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[3])(fra.me.REG[3], fra.me.REG[2]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[3])(fra.me.REG[3], fra.me.REG[1]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[3])(fra.me.REG[3], fra.me.REG[4]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[3])(fra.me.REG[3], fra.me.REG[5]);
  fra.me.REG[3] = NEW_Quadrilatere_polygone___Quadrilatere___init(fra.me.REG[3]);
  /* ./main.nit:22 */
  REGB0 = TAG_Int(3);
  fra.me.REG[6] = NEW_Array_array___Array___with_capacity(REGB0);
  if (!once_value_5) {
    fra.me.REG[7] = BOX_NativeString("Perimetre ");
    REGB0 = TAG_Int(10);
    fra.me.REG[7] = NEW_String_string___String___with_native(fra.me.REG[7], REGB0);
    once_value_5 = fra.me.REG[7];
    register_static_object(&once_value_5);
  } else fra.me.REG[7] = once_value_5;
  fra.me.REG[7] = fra.me.REG[7];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[7]);
  fra.me.REG[7] = CALL_figure___Figure___perimetre(fra.me.REG[3])(fra.me.REG[3]);
  fra.me.REG[7] = CALL_string___Object___to_s(fra.me.REG[7])(fra.me.REG[7]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[7]);
  if (!once_value_6) {
    fra.me.REG[7] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[7] = NEW_String_string___String___with_native(fra.me.REG[7], REGB0);
    once_value_6 = fra.me.REG[7];
    register_static_object(&once_value_6);
  } else fra.me.REG[7] = once_value_6;
  fra.me.REG[7] = fra.me.REG[7];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[7]);
  fra.me.REG[6] = CALL_string___Object___to_s(fra.me.REG[6])(fra.me.REG[6]);
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[6]);
  /* ./main.nit:23 */
  REGB0 = TAG_Int(4);
  fra.me.REG[6] = NEW_Array_array___Array___with_capacity(REGB0);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[2]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[1]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[4]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[5]);
  fra.me.REG[6] = NEW_Parallelogramme_polygone___Parallelogramme___init(fra.me.REG[6]);
  /* ./main.nit:24 */
  REGB0 = TAG_Int(3);
  fra.me.REG[7] = NEW_Array_array___Array___with_capacity(REGB0);
  if (!once_value_7) {
    fra.me.REG[8] = BOX_NativeString("Aire parallelogramme ");
    REGB0 = TAG_Int(21);
    fra.me.REG[8] = NEW_String_string___String___with_native(fra.me.REG[8], REGB0);
    once_value_7 = fra.me.REG[8];
    register_static_object(&once_value_7);
  } else fra.me.REG[8] = once_value_7;
  fra.me.REG[8] = fra.me.REG[8];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[8]);
  fra.me.REG[6] = CALL_figure___Figure___aire(fra.me.REG[6])(fra.me.REG[6]);
  fra.me.REG[6] = CALL_string___Object___to_s(fra.me.REG[6])(fra.me.REG[6]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[6]);
  if (!once_value_8) {
    fra.me.REG[6] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[6] = NEW_String_string___String___with_native(fra.me.REG[6], REGB0);
    once_value_8 = fra.me.REG[6];
    register_static_object(&once_value_8);
  } else fra.me.REG[6] = once_value_8;
  fra.me.REG[6] = fra.me.REG[6];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[6]);
  fra.me.REG[7] = CALL_string___Object___to_s(fra.me.REG[7])(fra.me.REG[7]);
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
  /* ./main.nit:25 */
  REGB0 = TAG_Int(4);
  fra.me.REG[7] = NEW_Array_array___Array___with_capacity(REGB0);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[2]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[1]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[4]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[5]);
  fra.me.REG[7] = NEW_Losange_polygone___Losange___init(fra.me.REG[7]);
  /* ./main.nit:26 */
  REGB0 = TAG_Int(3);
  fra.me.REG[6] = NEW_Array_array___Array___with_capacity(REGB0);
  if (!once_value_9) {
    fra.me.REG[8] = BOX_NativeString("Aire losange ");
    REGB0 = TAG_Int(13);
    fra.me.REG[8] = NEW_String_string___String___with_native(fra.me.REG[8], REGB0);
    once_value_9 = fra.me.REG[8];
    register_static_object(&once_value_9);
  } else fra.me.REG[8] = once_value_9;
  fra.me.REG[8] = fra.me.REG[8];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[8]);
  fra.me.REG[8] = CALL_figure___Figure___aire(fra.me.REG[7])(fra.me.REG[7]);
  fra.me.REG[8] = CALL_string___Object___to_s(fra.me.REG[8])(fra.me.REG[8]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[8]);
  if (!once_value_10) {
    fra.me.REG[8] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[8] = NEW_String_string___String___with_native(fra.me.REG[8], REGB0);
    once_value_10 = fra.me.REG[8];
    register_static_object(&once_value_10);
  } else fra.me.REG[8] = once_value_10;
  fra.me.REG[8] = fra.me.REG[8];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[8]);
  fra.me.REG[6] = CALL_string___Object___to_s(fra.me.REG[6])(fra.me.REG[6]);
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[6]);
  /* ./main.nit:27 */
  CALL_polygone___Losange___rectangleInscrit(fra.me.REG[7])(fra.me.REG[7]);
  /* ./main.nit:28 */
  CALL_polygone___Losange___cercleInscrit(fra.me.REG[7])(fra.me.REG[7]);
  /* ./main.nit:30 */
  REGB0 = TAG_Int(4);
  fra.me.REG[7] = NEW_Array_array___Array___with_capacity(REGB0);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[2]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[1]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[4]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[5]);
  fra.me.REG[7] = NEW_Rectangle_polygone___Rectangle___init(fra.me.REG[7]);
  /* ./main.nit:31 */
  fra.me.REG[6] = CALL_figure___Figure___aire(fra.me.REG[7])(fra.me.REG[7]);
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[6]);
  /* ./main.nit:33 */
  REGB0 = TAG_Int(4);
  fra.me.REG[6] = NEW_Array_array___Array___with_capacity(REGB0);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[2]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[1]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[4]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[5]);
  fra.me.REG[6] = NEW_Carre_polygone___Carre___init(fra.me.REG[6]);
  /* ./main.nit:34 */
  fra.me.REG[8] = CALL_figure___Figure___perimetre(fra.me.REG[6])(fra.me.REG[6]);
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[8]);
  /* ./main.nit:36 */
  REGB0 = TAG_Bool(IS_EQUAL_OO(fra.me.REG[7],fra.me.REG[6]));
  if (UNTAG_Bool(REGB0)) {
  } else {
    REGB1 = CALL_kernel___Object_____eqeq(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[6]);
    REGB0 = REGB1;
  }
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], REGB0);
  /* ./main.nit:37 */
  REGB0 = TAG_Bool(IS_EQUAL_OO(fra.me.REG[6],fra.me.REG[7]));
  if (UNTAG_Bool(REGB0)) {
  } else {
    REGB1 = CALL_kernel___Object_____eqeq(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[7]);
    REGB0 = REGB1;
  }
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], REGB0);
  /* ./main.nit:39 */
  fra.me.REG[7] = NEW_Fabrique_factory___Fabrique___init();
  /* ./main.nit:40 */
  REGB0 = TAG_Int(4);
  fra.me.REG[6] = NEW_Array_array___Array___with_capacity(REGB0);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[2]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[1]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[4]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[5]);
  fra.me.REG[6] = CALL_factory___Fabrique___creerPolygone(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[6]);
  /* ./main.nit:41 */
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[6]);
  /* ./main.nit:42 */
  REGB0 = TAG_Bool(VAL_ISA(fra.me.REG[6], COLOR_Rectangle, ID_Rectangle)) /*cast Rectangle*/;
  if (UNTAG_Bool(REGB0)) {
    /* ./main.nit:43 */
    if (!once_value_11) {
      fra.me.REG[7] = BOX_NativeString("grace au type adaptif il nous est possible d'appeler une méthode du type dynamique");
      REGB0 = TAG_Int(83);
      fra.me.REG[7] = NEW_String_string___String___with_native(fra.me.REG[7], REGB0);
      once_value_11 = fra.me.REG[7];
      register_static_object(&once_value_11);
    } else fra.me.REG[7] = once_value_11;
    fra.me.REG[7] = fra.me.REG[7];
    CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
    /* ./main.nit:44 */
    fra.me.REG[6] = CALL_polygone___Rectangle___cercleCirconscrit(fra.me.REG[6])(fra.me.REG[6]);
    CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[6]);
  }
  /* ./main.nit:48 */
  REGB0 = TAG_Int(4);
  fra.me.REG[6] = NEW_Array_array___Array___with_capacity(REGB0);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[5]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[4]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[1]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[2]);
  fra.me.REG[6] = NEW_Quadrilatere_polygone___Quadrilatere___init(fra.me.REG[6]);
  /* ./main.nit:49 */
  REGB0 = TAG_Bool(IS_EQUAL_OO(fra.me.REG[3],fra.me.REG[6]));
  if (UNTAG_Bool(REGB0)) {
  } else {
    REGB1 = CALL_kernel___Object_____eqeq(fra.me.REG[3])(fra.me.REG[3], fra.me.REG[6]);
    REGB0 = REGB1;
  }
  if (UNTAG_Bool(REGB0)) {
    if (!once_value_12) {
      fra.me.REG[6] = BOX_NativeString("Les deux figures sont semblables.");
      REGB0 = TAG_Int(33);
      fra.me.REG[6] = NEW_String_string___String___with_native(fra.me.REG[6], REGB0);
      once_value_12 = fra.me.REG[6];
      register_static_object(&once_value_12);
    } else fra.me.REG[6] = once_value_12;
    fra.me.REG[6] = fra.me.REG[6];
    CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[6]);
  }
  stack_frame_head = fra.me.prev;
  return;
}
