/* This C header file is generated by NIT to compile modules and programs that requires main. */
#ifndef main_sep
#define main_sep
#include "factory._sep.h"
#include <nit_common.h>
extern const char *LOCATE_main;
extern const int SFT_main[];
static const char * const LOCATE_main___Sys___main = "main::Sys::(kernel::Sys::main)";
void main___Sys___main(val_t p0);
typedef void (*main___Sys___main_t)(val_t p0);
val_t NEW_Sys_kernel___Sys___init();
#endif
