/* This C file is generated by NIT to compile module test. */
#include "test._sep.h"
void test___Sys___main(val_t p0){
  struct {struct stack_frame_t me; val_t MORE_REG[12];} fra;
  val_t REGB0;
  val_t REGB1;
  val_t REGB2;
  val_t tmp;
  static val_t once_value_1; /* Once value */
  static val_t once_value_2; /* Once value */
  static val_t once_value_3; /* Once value */
  static val_t once_value_4; /* Once value */
  static val_t once_value_5; /* Once value */
  static val_t once_value_6; /* Once value */
  static val_t once_value_7; /* Once value */
  static val_t once_value_8; /* Once value */
  static val_t once_value_9; /* Once value */
  static val_t once_value_10; /* Once value */
  static val_t once_value_11; /* Once value */
  static val_t once_value_12; /* Once value */
  static val_t once_value_13; /* Once value */
  static val_t once_value_14; /* Once value */
  static val_t once_value_15; /* Once value */
  static val_t once_value_16; /* Once value */
  static val_t once_value_17; /* Once value */
  static val_t once_value_18; /* Once value */
  static val_t once_value_19; /* Once value */
  static val_t once_value_20; /* Once value */
  static val_t once_value_21; /* Once value */
  static val_t once_value_22; /* Once value */
  static val_t once_value_23; /* Once value */
  static val_t once_value_24; /* Once value */
  static val_t once_value_25; /* Once value */
  static val_t once_value_26; /* Once value */
  static val_t once_value_27; /* Once value */
  static val_t once_value_28; /* Once value */
  static val_t once_value_29; /* Once value */
  static val_t once_value_30; /* Once value */
  static val_t once_value_31; /* Once value */
  static val_t once_value_32; /* Once value */
  static val_t once_value_33; /* Once value */
  static val_t once_value_34; /* Once value */
  static val_t once_value_35; /* Once value */
  static val_t once_value_36; /* Once value */
  static val_t once_value_37; /* Once value */
  static val_t once_value_38; /* Once value */
  static val_t once_value_39; /* Once value */
  static val_t once_value_40; /* Once value */
  static val_t once_value_41; /* Once value */
  static val_t once_value_42; /* Once value */
  static val_t once_value_43; /* Once value */
  static val_t once_value_44; /* Once value */
  static val_t once_value_45; /* Once value */
  static val_t once_value_46; /* Once value */
  static val_t once_value_47; /* Once value */
  static val_t once_value_48; /* Once value */
  static val_t once_value_49; /* Once value */
  static val_t once_value_50; /* Once value */
  static val_t once_value_51; /* Once value */
  static val_t once_value_52; /* Once value */
  static val_t once_value_53; /* Once value */
  static val_t once_value_54; /* Once value */
  static val_t once_value_55; /* Once value */
  static val_t once_value_56; /* Once value */
  static val_t once_value_57; /* Once value */
  static val_t once_value_58; /* Once value */
  static val_t once_value_59; /* Once value */
  static val_t once_value_60; /* Once value */
  static val_t once_value_61; /* Once value */
  static val_t once_value_62; /* Once value */
  static val_t once_value_63; /* Once value */
  static val_t once_value_64; /* Once value */
  static val_t once_value_65; /* Once value */
  static val_t once_value_66; /* Once value */
  static val_t once_value_67; /* Once value */
  static val_t once_value_69; /* Once value */
  static val_t once_value_70; /* Once value */
  static val_t once_value_72; /* Once value */
  static val_t once_value_73; /* Once value */
  static val_t once_value_75; /* Once value */
  static val_t once_value_76; /* Once value */
  static val_t once_value_77; /* Once value */
  static val_t once_value_78; /* Once value */
  static val_t once_value_79; /* Once value */
  static val_t once_value_81; /* Once value */
  static val_t once_value_82; /* Once value */
  static val_t once_value_84; /* Once value */
  static val_t once_value_85; /* Once value */
  static val_t once_value_87; /* Once value */
  static val_t once_value_88; /* Once value */
  static val_t once_value_89; /* Once value */
  static val_t once_value_90; /* Once value */
  static val_t once_value_91; /* Once value */
  static val_t once_value_92; /* Once value */
  static val_t once_value_93; /* Once value */
  static val_t once_value_94; /* Once value */
  static val_t once_value_95; /* Once value */
  static val_t once_value_96; /* Once value */
  static val_t once_value_97; /* Once value */
  static val_t once_value_98; /* Once value */
  static val_t once_value_99; /* Once value */
  static val_t once_value_100; /* Once value */
  static val_t once_value_101; /* Once value */
  static val_t once_value_102; /* Once value */
  static val_t once_value_103; /* Once value */
  static val_t once_value_104; /* Once value */
  static val_t once_value_105; /* Once value */
  static val_t once_value_106; /* Once value */
  static val_t once_value_107; /* Once value */
  static val_t once_value_108; /* Once value */
  static val_t once_value_109; /* Once value */
  static val_t once_value_110; /* Once value */
  static val_t once_value_111; /* Once value */
  static val_t once_value_112; /* Once value */
  static val_t once_value_113; /* Once value */
  static val_t once_value_114; /* Once value */
  static val_t once_value_115; /* Once value */
  static val_t once_value_116; /* Once value */
  static val_t once_value_117; /* Once value */
  static val_t once_value_118; /* Once value */
  static val_t once_value_119; /* Once value */
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_test;
  fra.me.line = 3;
  fra.me.meth = LOCATE_test___Sys___main;
  fra.me.has_broke = 0;
  fra.me.REG_size = 13;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[2] = NIT_NULL;
  fra.me.REG[3] = NIT_NULL;
  fra.me.REG[4] = NIT_NULL;
  fra.me.REG[5] = NIT_NULL;
  fra.me.REG[6] = NIT_NULL;
  fra.me.REG[7] = NIT_NULL;
  fra.me.REG[8] = NIT_NULL;
  fra.me.REG[9] = NIT_NULL;
  fra.me.REG[10] = NIT_NULL;
  fra.me.REG[11] = NIT_NULL;
  fra.me.REG[12] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* ./test.nit:3 */
  if (!once_value_1) {
    fra.me.REG[1] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[1] = NEW_String_string___String___with_native(fra.me.REG[1], REGB0);
    once_value_1 = fra.me.REG[1];
    register_static_object(&once_value_1);
  } else fra.me.REG[1] = once_value_1;
  fra.me.REG[1] = fra.me.REG[1];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[1]);
  /* ./test.nit:5 */
  fra.me.REG[1] = BOX_Float(0.0);
  fra.me.REG[2] = BOX_Float(5.0);
  fra.me.REG[2] = NEW_Point_figure___Point___init(fra.me.REG[1], fra.me.REG[2]);
  /* ./test.nit:6 */
  fra.me.REG[1] = BOX_Float(5.0);
  fra.me.REG[3] = BOX_Float(5.0);
  fra.me.REG[3] = NEW_Point_figure___Point___init(fra.me.REG[1], fra.me.REG[3]);
  /* ./test.nit:7 */
  fra.me.REG[1] = BOX_Float(5.0);
  fra.me.REG[4] = BOX_Float(0.0);
  fra.me.REG[4] = NEW_Point_figure___Point___init(fra.me.REG[1], fra.me.REG[4]);
  /* ./test.nit:8 */
  fra.me.REG[1] = BOX_Float(0.0);
  fra.me.REG[5] = BOX_Float(0.0);
  fra.me.REG[5] = NEW_Point_figure___Point___init(fra.me.REG[1], fra.me.REG[5]);
  /* ./test.nit:11 */
  if (!once_value_2) {
    fra.me.REG[1] = BOX_NativeString("Obtenir un point à partir de ses coordonnées cartésiennes.");
    REGB0 = TAG_Int(61);
    fra.me.REG[1] = NEW_String_string___String___with_native(fra.me.REG[1], REGB0);
    once_value_2 = fra.me.REG[1];
    register_static_object(&once_value_2);
  } else fra.me.REG[1] = once_value_2;
  fra.me.REG[1] = fra.me.REG[1];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[1]);
  /* ./test.nit:12 */
  if (!once_value_3) {
    fra.me.REG[1] = BOX_NativeString("Point 1");
    REGB0 = TAG_Int(7);
    fra.me.REG[1] = NEW_String_string___String___with_native(fra.me.REG[1], REGB0);
    once_value_3 = fra.me.REG[1];
    register_static_object(&once_value_3);
  } else fra.me.REG[1] = once_value_3;
  fra.me.REG[1] = fra.me.REG[1];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[1]);
  /* ./test.nit:13 */
  fra.me.REG[1] = BOX_Float(0.0);
  fra.me.REG[6] = BOX_Float(20.0);
  fra.me.REG[6] = NEW_Point_figure___Point___init(fra.me.REG[1], fra.me.REG[6]);
  /* ./test.nit:14 */
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[6]);
  /* ./test.nit:15 */
  fra.me.REG[1] = BOX_Float(0.5);
  fra.me.REG[7] = BOX_Float(10.0);
  /* /Users/tony/Projects/nit/lib/standard//kernel.nit:191 */
  fra.me.REG[7] = BOX_Float(-UNBOX_Float(fra.me.REG[7]));
  /* ./test.nit:15 */
  fra.me.REG[7] = NEW_Point_figure___Point___init(fra.me.REG[1], fra.me.REG[7]);
  /* ./test.nit:16 */
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
  /* ./test.nit:18 */
  if (!once_value_4) {
    fra.me.REG[1] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[1] = NEW_String_string___String___with_native(fra.me.REG[1], REGB0);
    once_value_4 = fra.me.REG[1];
    register_static_object(&once_value_4);
  } else fra.me.REG[1] = once_value_4;
  fra.me.REG[1] = fra.me.REG[1];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[1]);
  /* ./test.nit:19 */
  if (!once_value_5) {
    fra.me.REG[1] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[1] = NEW_String_string___String___with_native(fra.me.REG[1], REGB0);
    once_value_5 = fra.me.REG[1];
    register_static_object(&once_value_5);
  } else fra.me.REG[1] = once_value_5;
  fra.me.REG[1] = fra.me.REG[1];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[1]);
  /* ./test.nit:22 */
  REGB0 = TAG_Int(2);
  fra.me.REG[1] = NEW_Array_array___Array___with_capacity(REGB0);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[6]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[1])(fra.me.REG[1], fra.me.REG[7]);
  fra.me.REG[1] = NEW_Segment_figure___Segment___init(fra.me.REG[1]);
  /* ./test.nit:25 */
  if (!once_value_6) {
    fra.me.REG[8] = BOX_NativeString("Obtenir un polygone à partir de la liste de ses sommets.");
    REGB0 = TAG_Int(57);
    fra.me.REG[8] = NEW_String_string___String___with_native(fra.me.REG[8], REGB0);
    once_value_6 = fra.me.REG[8];
    register_static_object(&once_value_6);
  } else fra.me.REG[8] = once_value_6;
  fra.me.REG[8] = fra.me.REG[8];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[8]);
  /* ./test.nit:26 */
  REGB0 = TAG_Int(4);
  fra.me.REG[8] = NEW_Array_array___Array___with_capacity(REGB0);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[8])(fra.me.REG[8], fra.me.REG[2]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[8])(fra.me.REG[8], fra.me.REG[3]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[8])(fra.me.REG[8], fra.me.REG[4]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[8])(fra.me.REG[8], fra.me.REG[5]);
  fra.me.REG[8] = NEW_Carre_polygone___Carre___init(fra.me.REG[8]);
  /* ./test.nit:27 */
  if (!once_value_7) {
    fra.me.REG[9] = BOX_NativeString("Carré");
    REGB0 = TAG_Int(6);
    fra.me.REG[9] = NEW_String_string___String___with_native(fra.me.REG[9], REGB0);
    once_value_7 = fra.me.REG[9];
    register_static_object(&once_value_7);
  } else fra.me.REG[9] = once_value_7;
  fra.me.REG[9] = fra.me.REG[9];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[9]);
  /* ./test.nit:28 */
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[8]);
  /* ./test.nit:29 */
  if (!once_value_8) {
    fra.me.REG[9] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[9] = NEW_String_string___String___with_native(fra.me.REG[9], REGB0);
    once_value_8 = fra.me.REG[9];
    register_static_object(&once_value_8);
  } else fra.me.REG[9] = once_value_8;
  fra.me.REG[9] = fra.me.REG[9];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[9]);
  /* ./test.nit:30 */
  REGB0 = TAG_Int(4);
  fra.me.REG[9] = NEW_Array_array___Array___with_capacity(REGB0);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[9])(fra.me.REG[9], fra.me.REG[2]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[9])(fra.me.REG[9], fra.me.REG[5]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[9])(fra.me.REG[9], fra.me.REG[4]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[9])(fra.me.REG[9], fra.me.REG[3]);
  fra.me.REG[9] = NEW_Losange_polygone___Losange___init(fra.me.REG[9]);
  /* ./test.nit:31 */
  if (!once_value_9) {
    fra.me.REG[10] = BOX_NativeString("Losange");
    REGB0 = TAG_Int(7);
    fra.me.REG[10] = NEW_String_string___String___with_native(fra.me.REG[10], REGB0);
    once_value_9 = fra.me.REG[10];
    register_static_object(&once_value_9);
  } else fra.me.REG[10] = once_value_9;
  fra.me.REG[10] = fra.me.REG[10];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[10]);
  /* ./test.nit:32 */
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[9]);
  /* ./test.nit:33 */
  if (!once_value_10) {
    fra.me.REG[10] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[10] = NEW_String_string___String___with_native(fra.me.REG[10], REGB0);
    once_value_10 = fra.me.REG[10];
    register_static_object(&once_value_10);
  } else fra.me.REG[10] = once_value_10;
  fra.me.REG[10] = fra.me.REG[10];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[10]);
  /* ./test.nit:34 */
  REGB0 = TAG_Int(4);
  fra.me.REG[10] = NEW_Array_array___Array___with_capacity(REGB0);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[10])(fra.me.REG[10], fra.me.REG[2]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[10])(fra.me.REG[10], fra.me.REG[3]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[10])(fra.me.REG[10], fra.me.REG[4]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[10])(fra.me.REG[10], fra.me.REG[5]);
  fra.me.REG[10] = NEW_Rectangle_polygone___Rectangle___init(fra.me.REG[10]);
  /* ./test.nit:35 */
  if (!once_value_11) {
    fra.me.REG[11] = BOX_NativeString("Rectangle");
    REGB0 = TAG_Int(9);
    fra.me.REG[11] = NEW_String_string___String___with_native(fra.me.REG[11], REGB0);
    once_value_11 = fra.me.REG[11];
    register_static_object(&once_value_11);
  } else fra.me.REG[11] = once_value_11;
  fra.me.REG[11] = fra.me.REG[11];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[11]);
  /* ./test.nit:36 */
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[10]);
  /* ./test.nit:38 */
  if (!once_value_12) {
    fra.me.REG[11] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[11] = NEW_String_string___String___with_native(fra.me.REG[11], REGB0);
    once_value_12 = fra.me.REG[11];
    register_static_object(&once_value_12);
  } else fra.me.REG[11] = once_value_12;
  fra.me.REG[11] = fra.me.REG[11];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[11]);
  /* ./test.nit:39 */
  if (!once_value_13) {
    fra.me.REG[11] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[11] = NEW_String_string___String___with_native(fra.me.REG[11], REGB0);
    once_value_13 = fra.me.REG[11];
    register_static_object(&once_value_13);
  } else fra.me.REG[11] = once_value_13;
  fra.me.REG[11] = fra.me.REG[11];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[11]);
  /* ./test.nit:43 */
  if (!once_value_14) {
    fra.me.REG[11] = BOX_NativeString("Obtenir un cercle à partir d’un centre et d’un rayon.");
    REGB0 = TAG_Int(58);
    fra.me.REG[11] = NEW_String_string___String___with_native(fra.me.REG[11], REGB0);
    once_value_14 = fra.me.REG[11];
    register_static_object(&once_value_14);
  } else fra.me.REG[11] = once_value_14;
  fra.me.REG[11] = fra.me.REG[11];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[11]);
  /* ./test.nit:44 */
  if (!once_value_15) {
    fra.me.REG[11] = BOX_NativeString("Cercle");
    REGB0 = TAG_Int(6);
    fra.me.REG[11] = NEW_String_string___String___with_native(fra.me.REG[11], REGB0);
    once_value_15 = fra.me.REG[11];
    register_static_object(&once_value_15);
  } else fra.me.REG[11] = once_value_15;
  fra.me.REG[11] = fra.me.REG[11];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[11]);
  /* ./test.nit:45 */
  fra.me.REG[11] = BOX_Float(5.0);
  fra.me.REG[11] = NEW_Cercle_figure___Cercle___init(fra.me.REG[6], fra.me.REG[11]);
  /* ./test.nit:46 */
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[11]);
  /* ./test.nit:48 */
  if (!once_value_16) {
    fra.me.REG[6] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[6] = NEW_String_string___String___with_native(fra.me.REG[6], REGB0);
    once_value_16 = fra.me.REG[6];
    register_static_object(&once_value_16);
  } else fra.me.REG[6] = once_value_16;
  fra.me.REG[6] = fra.me.REG[6];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[6]);
  /* ./test.nit:49 */
  if (!once_value_17) {
    fra.me.REG[6] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[6] = NEW_String_string___String___with_native(fra.me.REG[6], REGB0);
    once_value_17 = fra.me.REG[6];
    register_static_object(&once_value_17);
  } else fra.me.REG[6] = once_value_17;
  fra.me.REG[6] = fra.me.REG[6];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[6]);
  /* ./test.nit:52 */
  if (!once_value_18) {
    fra.me.REG[6] = BOX_NativeString("Calculer l’aire et le périmètre d’une figure.");
    REGB0 = TAG_Int(51);
    fra.me.REG[6] = NEW_String_string___String___with_native(fra.me.REG[6], REGB0);
    once_value_18 = fra.me.REG[6];
    register_static_object(&once_value_18);
  } else fra.me.REG[6] = once_value_18;
  fra.me.REG[6] = fra.me.REG[6];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[6]);
  /* ./test.nit:53 */
  REGB0 = TAG_Int(3);
  fra.me.REG[6] = NEW_Array_array___Array___with_capacity(REGB0);
  if (!once_value_19) {
    fra.me.REG[12] = BOX_NativeString("Aire d'un carré  ");
    REGB0 = TAG_Int(18);
    fra.me.REG[12] = NEW_String_string___String___with_native(fra.me.REG[12], REGB0);
    once_value_19 = fra.me.REG[12];
    register_static_object(&once_value_19);
  } else fra.me.REG[12] = once_value_19;
  fra.me.REG[12] = fra.me.REG[12];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[12]);
  fra.me.REG[12] = CALL_figure___Figure___aire(fra.me.REG[8])(fra.me.REG[8]);
  fra.me.REG[12] = CALL_string___Object___to_s(fra.me.REG[12])(fra.me.REG[12]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[12]);
  if (!once_value_20) {
    fra.me.REG[12] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[12] = NEW_String_string___String___with_native(fra.me.REG[12], REGB0);
    once_value_20 = fra.me.REG[12];
    register_static_object(&once_value_20);
  } else fra.me.REG[12] = once_value_20;
  fra.me.REG[12] = fra.me.REG[12];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[12]);
  fra.me.REG[6] = CALL_string___Object___to_s(fra.me.REG[6])(fra.me.REG[6]);
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[6]);
  /* ./test.nit:54 */
  REGB0 = TAG_Int(3);
  fra.me.REG[6] = NEW_Array_array___Array___with_capacity(REGB0);
  if (!once_value_21) {
    fra.me.REG[12] = BOX_NativeString("Périmètre d'un carré  ");
    REGB0 = TAG_Int(25);
    fra.me.REG[12] = NEW_String_string___String___with_native(fra.me.REG[12], REGB0);
    once_value_21 = fra.me.REG[12];
    register_static_object(&once_value_21);
  } else fra.me.REG[12] = once_value_21;
  fra.me.REG[12] = fra.me.REG[12];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[12]);
  fra.me.REG[12] = CALL_figure___Figure___perimetre(fra.me.REG[8])(fra.me.REG[8]);
  fra.me.REG[12] = CALL_string___Object___to_s(fra.me.REG[12])(fra.me.REG[12]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[12]);
  if (!once_value_22) {
    fra.me.REG[12] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[12] = NEW_String_string___String___with_native(fra.me.REG[12], REGB0);
    once_value_22 = fra.me.REG[12];
    register_static_object(&once_value_22);
  } else fra.me.REG[12] = once_value_22;
  fra.me.REG[12] = fra.me.REG[12];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[12]);
  fra.me.REG[6] = CALL_string___Object___to_s(fra.me.REG[6])(fra.me.REG[6]);
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[6]);
  /* ./test.nit:55 */
  if (!once_value_23) {
    fra.me.REG[6] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[6] = NEW_String_string___String___with_native(fra.me.REG[6], REGB0);
    once_value_23 = fra.me.REG[6];
    register_static_object(&once_value_23);
  } else fra.me.REG[6] = once_value_23;
  fra.me.REG[6] = fra.me.REG[6];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[6]);
  /* ./test.nit:56 */
  REGB0 = TAG_Int(3);
  fra.me.REG[6] = NEW_Array_array___Array___with_capacity(REGB0);
  if (!once_value_24) {
    fra.me.REG[12] = BOX_NativeString("Aire d'un losange  ");
    REGB0 = TAG_Int(19);
    fra.me.REG[12] = NEW_String_string___String___with_native(fra.me.REG[12], REGB0);
    once_value_24 = fra.me.REG[12];
    register_static_object(&once_value_24);
  } else fra.me.REG[12] = once_value_24;
  fra.me.REG[12] = fra.me.REG[12];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[12]);
  fra.me.REG[12] = CALL_figure___Figure___aire(fra.me.REG[9])(fra.me.REG[9]);
  fra.me.REG[12] = CALL_string___Object___to_s(fra.me.REG[12])(fra.me.REG[12]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[12]);
  if (!once_value_25) {
    fra.me.REG[12] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[12] = NEW_String_string___String___with_native(fra.me.REG[12], REGB0);
    once_value_25 = fra.me.REG[12];
    register_static_object(&once_value_25);
  } else fra.me.REG[12] = once_value_25;
  fra.me.REG[12] = fra.me.REG[12];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[12]);
  fra.me.REG[6] = CALL_string___Object___to_s(fra.me.REG[6])(fra.me.REG[6]);
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[6]);
  /* ./test.nit:57 */
  REGB0 = TAG_Int(3);
  fra.me.REG[6] = NEW_Array_array___Array___with_capacity(REGB0);
  if (!once_value_26) {
    fra.me.REG[12] = BOX_NativeString("Périmètre d'un losange  ");
    REGB0 = TAG_Int(26);
    fra.me.REG[12] = NEW_String_string___String___with_native(fra.me.REG[12], REGB0);
    once_value_26 = fra.me.REG[12];
    register_static_object(&once_value_26);
  } else fra.me.REG[12] = once_value_26;
  fra.me.REG[12] = fra.me.REG[12];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[12]);
  fra.me.REG[12] = CALL_figure___Figure___perimetre(fra.me.REG[9])(fra.me.REG[9]);
  fra.me.REG[12] = CALL_string___Object___to_s(fra.me.REG[12])(fra.me.REG[12]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[12]);
  if (!once_value_27) {
    fra.me.REG[12] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[12] = NEW_String_string___String___with_native(fra.me.REG[12], REGB0);
    once_value_27 = fra.me.REG[12];
    register_static_object(&once_value_27);
  } else fra.me.REG[12] = once_value_27;
  fra.me.REG[12] = fra.me.REG[12];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[12]);
  fra.me.REG[6] = CALL_string___Object___to_s(fra.me.REG[6])(fra.me.REG[6]);
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[6]);
  /* ./test.nit:58 */
  if (!once_value_28) {
    fra.me.REG[6] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[6] = NEW_String_string___String___with_native(fra.me.REG[6], REGB0);
    once_value_28 = fra.me.REG[6];
    register_static_object(&once_value_28);
  } else fra.me.REG[6] = once_value_28;
  fra.me.REG[6] = fra.me.REG[6];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[6]);
  /* ./test.nit:59 */
  REGB0 = TAG_Int(3);
  fra.me.REG[6] = NEW_Array_array___Array___with_capacity(REGB0);
  if (!once_value_29) {
    fra.me.REG[12] = BOX_NativeString("Aire d'un rectangle  ");
    REGB0 = TAG_Int(21);
    fra.me.REG[12] = NEW_String_string___String___with_native(fra.me.REG[12], REGB0);
    once_value_29 = fra.me.REG[12];
    register_static_object(&once_value_29);
  } else fra.me.REG[12] = once_value_29;
  fra.me.REG[12] = fra.me.REG[12];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[12]);
  fra.me.REG[12] = CALL_figure___Figure___aire(fra.me.REG[10])(fra.me.REG[10]);
  fra.me.REG[12] = CALL_string___Object___to_s(fra.me.REG[12])(fra.me.REG[12]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[12]);
  if (!once_value_30) {
    fra.me.REG[12] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[12] = NEW_String_string___String___with_native(fra.me.REG[12], REGB0);
    once_value_30 = fra.me.REG[12];
    register_static_object(&once_value_30);
  } else fra.me.REG[12] = once_value_30;
  fra.me.REG[12] = fra.me.REG[12];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[12]);
  fra.me.REG[6] = CALL_string___Object___to_s(fra.me.REG[6])(fra.me.REG[6]);
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[6]);
  /* ./test.nit:60 */
  REGB0 = TAG_Int(3);
  fra.me.REG[6] = NEW_Array_array___Array___with_capacity(REGB0);
  if (!once_value_31) {
    fra.me.REG[12] = BOX_NativeString("Périmètre d'un rectangle ");
    REGB0 = TAG_Int(27);
    fra.me.REG[12] = NEW_String_string___String___with_native(fra.me.REG[12], REGB0);
    once_value_31 = fra.me.REG[12];
    register_static_object(&once_value_31);
  } else fra.me.REG[12] = once_value_31;
  fra.me.REG[12] = fra.me.REG[12];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[12]);
  fra.me.REG[12] = CALL_figure___Figure___perimetre(fra.me.REG[10])(fra.me.REG[10]);
  fra.me.REG[12] = CALL_string___Object___to_s(fra.me.REG[12])(fra.me.REG[12]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[12]);
  if (!once_value_32) {
    fra.me.REG[12] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[12] = NEW_String_string___String___with_native(fra.me.REG[12], REGB0);
    once_value_32 = fra.me.REG[12];
    register_static_object(&once_value_32);
  } else fra.me.REG[12] = once_value_32;
  fra.me.REG[12] = fra.me.REG[12];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[12]);
  fra.me.REG[6] = CALL_string___Object___to_s(fra.me.REG[6])(fra.me.REG[6]);
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[6]);
  /* ./test.nit:61 */
  if (!once_value_33) {
    fra.me.REG[6] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[6] = NEW_String_string___String___with_native(fra.me.REG[6], REGB0);
    once_value_33 = fra.me.REG[6];
    register_static_object(&once_value_33);
  } else fra.me.REG[6] = once_value_33;
  fra.me.REG[6] = fra.me.REG[6];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[6]);
  /* ./test.nit:62 */
  REGB0 = TAG_Int(3);
  fra.me.REG[6] = NEW_Array_array___Array___with_capacity(REGB0);
  if (!once_value_34) {
    fra.me.REG[12] = BOX_NativeString("Aire d'un cercle  ");
    REGB0 = TAG_Int(18);
    fra.me.REG[12] = NEW_String_string___String___with_native(fra.me.REG[12], REGB0);
    once_value_34 = fra.me.REG[12];
    register_static_object(&once_value_34);
  } else fra.me.REG[12] = once_value_34;
  fra.me.REG[12] = fra.me.REG[12];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[12]);
  fra.me.REG[12] = CALL_figure___Figure___aire(fra.me.REG[11])(fra.me.REG[11]);
  fra.me.REG[12] = CALL_string___Object___to_s(fra.me.REG[12])(fra.me.REG[12]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[12]);
  if (!once_value_35) {
    fra.me.REG[12] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[12] = NEW_String_string___String___with_native(fra.me.REG[12], REGB0);
    once_value_35 = fra.me.REG[12];
    register_static_object(&once_value_35);
  } else fra.me.REG[12] = once_value_35;
  fra.me.REG[12] = fra.me.REG[12];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[12]);
  fra.me.REG[6] = CALL_string___Object___to_s(fra.me.REG[6])(fra.me.REG[6]);
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[6]);
  /* ./test.nit:63 */
  REGB0 = TAG_Int(3);
  fra.me.REG[6] = NEW_Array_array___Array___with_capacity(REGB0);
  if (!once_value_36) {
    fra.me.REG[12] = BOX_NativeString("Périmètre d'un cercle ");
    REGB0 = TAG_Int(24);
    fra.me.REG[12] = NEW_String_string___String___with_native(fra.me.REG[12], REGB0);
    once_value_36 = fra.me.REG[12];
    register_static_object(&once_value_36);
  } else fra.me.REG[12] = once_value_36;
  fra.me.REG[12] = fra.me.REG[12];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[12]);
  fra.me.REG[12] = CALL_figure___Figure___perimetre(fra.me.REG[11])(fra.me.REG[11]);
  fra.me.REG[12] = CALL_string___Object___to_s(fra.me.REG[12])(fra.me.REG[12]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[12]);
  if (!once_value_37) {
    fra.me.REG[12] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[12] = NEW_String_string___String___with_native(fra.me.REG[12], REGB0);
    once_value_37 = fra.me.REG[12];
    register_static_object(&once_value_37);
  } else fra.me.REG[12] = once_value_37;
  fra.me.REG[12] = fra.me.REG[12];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[12]);
  fra.me.REG[6] = CALL_string___Object___to_s(fra.me.REG[6])(fra.me.REG[6]);
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[6]);
  /* ./test.nit:64 */
  if (!once_value_38) {
    fra.me.REG[6] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[6] = NEW_String_string___String___with_native(fra.me.REG[6], REGB0);
    once_value_38 = fra.me.REG[6];
    register_static_object(&once_value_38);
  } else fra.me.REG[6] = once_value_38;
  fra.me.REG[6] = fra.me.REG[6];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[6]);
  /* ./test.nit:65 */
  REGB0 = TAG_Int(3);
  fra.me.REG[6] = NEW_Array_array___Array___with_capacity(REGB0);
  if (!once_value_39) {
    fra.me.REG[12] = BOX_NativeString("Aire d'un point  ");
    REGB0 = TAG_Int(17);
    fra.me.REG[12] = NEW_String_string___String___with_native(fra.me.REG[12], REGB0);
    once_value_39 = fra.me.REG[12];
    register_static_object(&once_value_39);
  } else fra.me.REG[12] = once_value_39;
  fra.me.REG[12] = fra.me.REG[12];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[12]);
  fra.me.REG[12] = CALL_figure___Figure___aire(fra.me.REG[7])(fra.me.REG[7]);
  fra.me.REG[12] = CALL_string___Object___to_s(fra.me.REG[12])(fra.me.REG[12]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[12]);
  if (!once_value_40) {
    fra.me.REG[12] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[12] = NEW_String_string___String___with_native(fra.me.REG[12], REGB0);
    once_value_40 = fra.me.REG[12];
    register_static_object(&once_value_40);
  } else fra.me.REG[12] = once_value_40;
  fra.me.REG[12] = fra.me.REG[12];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[12]);
  fra.me.REG[6] = CALL_string___Object___to_s(fra.me.REG[6])(fra.me.REG[6]);
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[6]);
  /* ./test.nit:66 */
  REGB0 = TAG_Int(3);
  fra.me.REG[6] = NEW_Array_array___Array___with_capacity(REGB0);
  if (!once_value_41) {
    fra.me.REG[12] = BOX_NativeString("Périmètre d'un point  ");
    REGB0 = TAG_Int(24);
    fra.me.REG[12] = NEW_String_string___String___with_native(fra.me.REG[12], REGB0);
    once_value_41 = fra.me.REG[12];
    register_static_object(&once_value_41);
  } else fra.me.REG[12] = once_value_41;
  fra.me.REG[12] = fra.me.REG[12];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[12]);
  fra.me.REG[12] = CALL_figure___Figure___perimetre(fra.me.REG[7])(fra.me.REG[7]);
  fra.me.REG[12] = CALL_string___Object___to_s(fra.me.REG[12])(fra.me.REG[12]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[12]);
  if (!once_value_42) {
    fra.me.REG[12] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[12] = NEW_String_string___String___with_native(fra.me.REG[12], REGB0);
    once_value_42 = fra.me.REG[12];
    register_static_object(&once_value_42);
  } else fra.me.REG[12] = once_value_42;
  fra.me.REG[12] = fra.me.REG[12];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[6])(fra.me.REG[6], fra.me.REG[12]);
  fra.me.REG[6] = CALL_string___Object___to_s(fra.me.REG[6])(fra.me.REG[6]);
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[6]);
  /* ./test.nit:68 */
  if (!once_value_43) {
    fra.me.REG[6] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[6] = NEW_String_string___String___with_native(fra.me.REG[6], REGB0);
    once_value_43 = fra.me.REG[6];
    register_static_object(&once_value_43);
  } else fra.me.REG[6] = once_value_43;
  fra.me.REG[6] = fra.me.REG[6];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[6]);
  /* ./test.nit:69 */
  if (!once_value_44) {
    fra.me.REG[6] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[6] = NEW_String_string___String___with_native(fra.me.REG[6], REGB0);
    once_value_44 = fra.me.REG[6];
    register_static_object(&once_value_44);
  } else fra.me.REG[6] = once_value_44;
  fra.me.REG[6] = fra.me.REG[6];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[6]);
  /* ./test.nit:73 */
  if (!once_value_45) {
    fra.me.REG[6] = BOX_NativeString("Obtenir l’abscisse et l’ordonnée d’un point.");
    REGB0 = TAG_Int(51);
    fra.me.REG[6] = NEW_String_string___String___with_native(fra.me.REG[6], REGB0);
    once_value_45 = fra.me.REG[6];
    register_static_object(&once_value_45);
  } else fra.me.REG[6] = once_value_45;
  fra.me.REG[6] = fra.me.REG[6];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[6]);
  /* ./test.nit:74 */
  if (!once_value_46) {
    fra.me.REG[6] = BOX_NativeString("Abscisse");
    REGB0 = TAG_Int(8);
    fra.me.REG[6] = NEW_String_string___String___with_native(fra.me.REG[6], REGB0);
    once_value_46 = fra.me.REG[6];
    register_static_object(&once_value_46);
  } else fra.me.REG[6] = once_value_46;
  fra.me.REG[6] = fra.me.REG[6];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[6]);
  /* ./test.nit:75 */
  fra.me.REG[6] = CALL_figure___Point___x(fra.me.REG[7])(fra.me.REG[7]);
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[6]);
  /* ./test.nit:76 */
  if (!once_value_47) {
    fra.me.REG[6] = BOX_NativeString("Ordonnée");
    REGB0 = TAG_Int(9);
    fra.me.REG[6] = NEW_String_string___String___with_native(fra.me.REG[6], REGB0);
    once_value_47 = fra.me.REG[6];
    register_static_object(&once_value_47);
  } else fra.me.REG[6] = once_value_47;
  fra.me.REG[6] = fra.me.REG[6];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[6]);
  /* ./test.nit:77 */
  fra.me.REG[7] = CALL_figure___Point___y(fra.me.REG[7])(fra.me.REG[7]);
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
  /* ./test.nit:79 */
  if (!once_value_48) {
    fra.me.REG[7] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[7] = NEW_String_string___String___with_native(fra.me.REG[7], REGB0);
    once_value_48 = fra.me.REG[7];
    register_static_object(&once_value_48);
  } else fra.me.REG[7] = once_value_48;
  fra.me.REG[7] = fra.me.REG[7];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
  /* ./test.nit:80 */
  if (!once_value_49) {
    fra.me.REG[7] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[7] = NEW_String_string___String___with_native(fra.me.REG[7], REGB0);
    once_value_49 = fra.me.REG[7];
    register_static_object(&once_value_49);
  } else fra.me.REG[7] = once_value_49;
  fra.me.REG[7] = fra.me.REG[7];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
  /* ./test.nit:83 */
  if (!once_value_50) {
    fra.me.REG[7] = BOX_NativeString("Obtenir les sommets d’un polygone.");
    REGB0 = TAG_Int(36);
    fra.me.REG[7] = NEW_String_string___String___with_native(fra.me.REG[7], REGB0);
    once_value_50 = fra.me.REG[7];
    register_static_object(&once_value_50);
  } else fra.me.REG[7] = once_value_50;
  fra.me.REG[7] = fra.me.REG[7];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
  /* ./test.nit:84 */
  REGB0 = TAG_Int(3);
  fra.me.REG[7] = NEW_Array_array___Array___with_capacity(REGB0);
  if (!once_value_51) {
    fra.me.REG[6] = BOX_NativeString("Sommets d'un carré  ");
    REGB0 = TAG_Int(21);
    fra.me.REG[6] = NEW_String_string___String___with_native(fra.me.REG[6], REGB0);
    once_value_51 = fra.me.REG[6];
    register_static_object(&once_value_51);
  } else fra.me.REG[6] = once_value_51;
  fra.me.REG[6] = fra.me.REG[6];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[6]);
  fra.me.REG[8] = CALL_polygone___Polygone___sommets(fra.me.REG[8])(fra.me.REG[8]);
  fra.me.REG[8] = CALL_string___Object___to_s(fra.me.REG[8])(fra.me.REG[8]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[8]);
  if (!once_value_52) {
    fra.me.REG[8] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[8] = NEW_String_string___String___with_native(fra.me.REG[8], REGB0);
    once_value_52 = fra.me.REG[8];
    register_static_object(&once_value_52);
  } else fra.me.REG[8] = once_value_52;
  fra.me.REG[8] = fra.me.REG[8];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[8]);
  fra.me.REG[7] = CALL_string___Object___to_s(fra.me.REG[7])(fra.me.REG[7]);
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
  /* ./test.nit:85 */
  REGB0 = TAG_Int(3);
  fra.me.REG[7] = NEW_Array_array___Array___with_capacity(REGB0);
  if (!once_value_53) {
    fra.me.REG[8] = BOX_NativeString("Sommets d'un losange  ");
    REGB0 = TAG_Int(22);
    fra.me.REG[8] = NEW_String_string___String___with_native(fra.me.REG[8], REGB0);
    once_value_53 = fra.me.REG[8];
    register_static_object(&once_value_53);
  } else fra.me.REG[8] = once_value_53;
  fra.me.REG[8] = fra.me.REG[8];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[8]);
  fra.me.REG[1] = CALL_figure___Segment___sommets(fra.me.REG[1])(fra.me.REG[1]);
  fra.me.REG[1] = CALL_string___Object___to_s(fra.me.REG[1])(fra.me.REG[1]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[1]);
  if (!once_value_54) {
    fra.me.REG[1] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[1] = NEW_String_string___String___with_native(fra.me.REG[1], REGB0);
    once_value_54 = fra.me.REG[1];
    register_static_object(&once_value_54);
  } else fra.me.REG[1] = once_value_54;
  fra.me.REG[1] = fra.me.REG[1];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[1]);
  fra.me.REG[7] = CALL_string___Object___to_s(fra.me.REG[7])(fra.me.REG[7]);
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
  /* ./test.nit:86 */
  REGB0 = TAG_Int(3);
  fra.me.REG[7] = NEW_Array_array___Array___with_capacity(REGB0);
  if (!once_value_55) {
    fra.me.REG[1] = BOX_NativeString("Sommets d'un rectangle  ");
    REGB0 = TAG_Int(24);
    fra.me.REG[1] = NEW_String_string___String___with_native(fra.me.REG[1], REGB0);
    once_value_55 = fra.me.REG[1];
    register_static_object(&once_value_55);
  } else fra.me.REG[1] = once_value_55;
  fra.me.REG[1] = fra.me.REG[1];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[1]);
  fra.me.REG[1] = CALL_polygone___Polygone___sommets(fra.me.REG[10])(fra.me.REG[10]);
  fra.me.REG[1] = CALL_string___Object___to_s(fra.me.REG[1])(fra.me.REG[1]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[1]);
  if (!once_value_56) {
    fra.me.REG[1] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[1] = NEW_String_string___String___with_native(fra.me.REG[1], REGB0);
    once_value_56 = fra.me.REG[1];
    register_static_object(&once_value_56);
  } else fra.me.REG[1] = once_value_56;
  fra.me.REG[1] = fra.me.REG[1];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[1]);
  fra.me.REG[7] = CALL_string___Object___to_s(fra.me.REG[7])(fra.me.REG[7]);
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
  /* ./test.nit:88 */
  if (!once_value_57) {
    fra.me.REG[7] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[7] = NEW_String_string___String___with_native(fra.me.REG[7], REGB0);
    once_value_57 = fra.me.REG[7];
    register_static_object(&once_value_57);
  } else fra.me.REG[7] = once_value_57;
  fra.me.REG[7] = fra.me.REG[7];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
  /* ./test.nit:89 */
  if (!once_value_58) {
    fra.me.REG[7] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[7] = NEW_String_string___String___with_native(fra.me.REG[7], REGB0);
    once_value_58 = fra.me.REG[7];
    register_static_object(&once_value_58);
  } else fra.me.REG[7] = once_value_58;
  fra.me.REG[7] = fra.me.REG[7];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
  /* ./test.nit:92 */
  if (!once_value_59) {
    fra.me.REG[7] = BOX_NativeString("Obtenir le centre et le rayon d’un cercle.");
    REGB0 = TAG_Int(44);
    fra.me.REG[7] = NEW_String_string___String___with_native(fra.me.REG[7], REGB0);
    once_value_59 = fra.me.REG[7];
    register_static_object(&once_value_59);
  } else fra.me.REG[7] = once_value_59;
  fra.me.REG[7] = fra.me.REG[7];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
  /* ./test.nit:93 */
  REGB0 = TAG_Int(3);
  fra.me.REG[7] = NEW_Array_array___Array___with_capacity(REGB0);
  if (!once_value_60) {
    fra.me.REG[1] = BOX_NativeString("Centre d'un cercle  ");
    REGB0 = TAG_Int(20);
    fra.me.REG[1] = NEW_String_string___String___with_native(fra.me.REG[1], REGB0);
    once_value_60 = fra.me.REG[1];
    register_static_object(&once_value_60);
  } else fra.me.REG[1] = once_value_60;
  fra.me.REG[1] = fra.me.REG[1];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[1]);
  fra.me.REG[1] = CALL_figure___Cercle___centre(fra.me.REG[11])(fra.me.REG[11]);
  fra.me.REG[1] = CALL_string___Object___to_s(fra.me.REG[1])(fra.me.REG[1]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[1]);
  if (!once_value_61) {
    fra.me.REG[1] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[1] = NEW_String_string___String___with_native(fra.me.REG[1], REGB0);
    once_value_61 = fra.me.REG[1];
    register_static_object(&once_value_61);
  } else fra.me.REG[1] = once_value_61;
  fra.me.REG[1] = fra.me.REG[1];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[1]);
  fra.me.REG[7] = CALL_string___Object___to_s(fra.me.REG[7])(fra.me.REG[7]);
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
  /* ./test.nit:94 */
  REGB0 = TAG_Int(3);
  fra.me.REG[7] = NEW_Array_array___Array___with_capacity(REGB0);
  if (!once_value_62) {
    fra.me.REG[1] = BOX_NativeString("Rayon d'un cercle  ");
    REGB0 = TAG_Int(19);
    fra.me.REG[1] = NEW_String_string___String___with_native(fra.me.REG[1], REGB0);
    once_value_62 = fra.me.REG[1];
    register_static_object(&once_value_62);
  } else fra.me.REG[1] = once_value_62;
  fra.me.REG[1] = fra.me.REG[1];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[1]);
  fra.me.REG[11] = CALL_figure___Cercle___rayon(fra.me.REG[11])(fra.me.REG[11]);
  fra.me.REG[11] = CALL_string___Object___to_s(fra.me.REG[11])(fra.me.REG[11]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[11]);
  if (!once_value_63) {
    fra.me.REG[11] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[11] = NEW_String_string___String___with_native(fra.me.REG[11], REGB0);
    once_value_63 = fra.me.REG[11];
    register_static_object(&once_value_63);
  } else fra.me.REG[11] = once_value_63;
  fra.me.REG[11] = fra.me.REG[11];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[11]);
  fra.me.REG[7] = CALL_string___Object___to_s(fra.me.REG[7])(fra.me.REG[7]);
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
  /* ./test.nit:96 */
  if (!once_value_64) {
    fra.me.REG[7] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[7] = NEW_String_string___String___with_native(fra.me.REG[7], REGB0);
    once_value_64 = fra.me.REG[7];
    register_static_object(&once_value_64);
  } else fra.me.REG[7] = once_value_64;
  fra.me.REG[7] = fra.me.REG[7];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
  /* ./test.nit:97 */
  if (!once_value_65) {
    fra.me.REG[7] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[7] = NEW_String_string___String___with_native(fra.me.REG[7], REGB0);
    once_value_65 = fra.me.REG[7];
    register_static_object(&once_value_65);
  } else fra.me.REG[7] = once_value_65;
  fra.me.REG[7] = fra.me.REG[7];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
  /* ./test.nit:100 */
  if (!once_value_66) {
    fra.me.REG[7] = BOX_NativeString("Obtenir la taille de la longueur, de la largeur et de la diagonale d’un rectangle.");
    REGB0 = TAG_Int(84);
    fra.me.REG[7] = NEW_String_string___String___with_native(fra.me.REG[7], REGB0);
    once_value_66 = fra.me.REG[7];
    register_static_object(&once_value_66);
  } else fra.me.REG[7] = once_value_66;
  fra.me.REG[7] = fra.me.REG[7];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
  /* ./test.nit:101 */
  REGB0 = TAG_Int(3);
  fra.me.REG[7] = NEW_Array_array___Array___with_capacity(REGB0);
  if (!once_value_67) {
    fra.me.REG[11] = BOX_NativeString("Longeur d'un rectangle  ");
    REGB0 = TAG_Int(24);
    fra.me.REG[11] = NEW_String_string___String___with_native(fra.me.REG[11], REGB0);
    once_value_67 = fra.me.REG[11];
    register_static_object(&once_value_67);
  } else fra.me.REG[11] = once_value_67;
  fra.me.REG[11] = fra.me.REG[11];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[11]);
  fra.me.REG[11] = CALL_polygone___Polygone___cotes(fra.me.REG[10])(fra.me.REG[10]);
  REGB0 = TAG_Int(0);
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
  REGB1 = TAG_Int(0);
  /* /Users/tony/Projects/nit/lib/standard//kernel.nit:213 */
  REGB1 = TAG_Bool(UNTAG_Int(REGB0)>=UNTAG_Int(REGB1));
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
  if (UNTAG_Bool(REGB1)) {
    REGB1 = TAG_Bool(ATTR_array___AbstractArrayRead____length(fra.me.REG[11])!=NIT_NULL);
    if (UNTAG_Bool(REGB1)) {
    } else {
      nit_abort("Uninitialized attribute %s", "_length", LOCATE_array, 245);
    }
    REGB1 = ATTR_array___AbstractArrayRead____length(fra.me.REG[11]);
    /* /Users/tony/Projects/nit/lib/standard//kernel.nit:212 */
    REGB1 = TAG_Bool(UNTAG_Int(REGB0)<UNTAG_Int(REGB1));
  } else {
    /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
    REGB2 = TAG_Bool(false);
    REGB1 = REGB2;
  }
  if (UNTAG_Bool(REGB1)) {
  } else {
    nit_abort("Assert %s  failed", "'index'", LOCATE_array, 245);
  }
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
  fra.me.REG[11] = ATTR_array___Array____items(fra.me.REG[11]);
  REGB1 = TAG_Bool(fra.me.REG[11]==NIT_NULL);
  if (UNTAG_Bool(REGB1)) {
    nit_abort("Reciever is null", NULL, LOCATE_array, 246);
  }
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:654 */
  fra.me.REG[11] = ((Nit_NativeArray)fra.me.REG[11])->val[UNTAG_Int(REGB0)];
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
  goto label68;
  label68: while(0);
  /* ./test.nit:101 */
  REGB0 = TAG_Bool(fra.me.REG[11]==NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
    nit_abort("Reciever is null", NULL, LOCATE_test, 101);
  }
  fra.me.REG[11] = CALL_figure___Segment___taille(fra.me.REG[11])(fra.me.REG[11]);
  fra.me.REG[11] = CALL_string___Object___to_s(fra.me.REG[11])(fra.me.REG[11]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[11]);
  if (!once_value_69) {
    fra.me.REG[11] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[11] = NEW_String_string___String___with_native(fra.me.REG[11], REGB0);
    once_value_69 = fra.me.REG[11];
    register_static_object(&once_value_69);
  } else fra.me.REG[11] = once_value_69;
  fra.me.REG[11] = fra.me.REG[11];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[11]);
  fra.me.REG[7] = CALL_string___Object___to_s(fra.me.REG[7])(fra.me.REG[7]);
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
  /* ./test.nit:102 */
  REGB0 = TAG_Int(3);
  fra.me.REG[7] = NEW_Array_array___Array___with_capacity(REGB0);
  if (!once_value_70) {
    fra.me.REG[11] = BOX_NativeString("Largeur d'un rectangle  ");
    REGB0 = TAG_Int(24);
    fra.me.REG[11] = NEW_String_string___String___with_native(fra.me.REG[11], REGB0);
    once_value_70 = fra.me.REG[11];
    register_static_object(&once_value_70);
  } else fra.me.REG[11] = once_value_70;
  fra.me.REG[11] = fra.me.REG[11];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[11]);
  fra.me.REG[11] = CALL_polygone___Polygone___cotes(fra.me.REG[10])(fra.me.REG[10]);
  REGB0 = TAG_Int(1);
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
  REGB1 = TAG_Int(0);
  /* /Users/tony/Projects/nit/lib/standard//kernel.nit:213 */
  REGB1 = TAG_Bool(UNTAG_Int(REGB0)>=UNTAG_Int(REGB1));
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
  if (UNTAG_Bool(REGB1)) {
    REGB1 = TAG_Bool(ATTR_array___AbstractArrayRead____length(fra.me.REG[11])!=NIT_NULL);
    if (UNTAG_Bool(REGB1)) {
    } else {
      nit_abort("Uninitialized attribute %s", "_length", LOCATE_array, 245);
    }
    REGB1 = ATTR_array___AbstractArrayRead____length(fra.me.REG[11]);
    /* /Users/tony/Projects/nit/lib/standard//kernel.nit:212 */
    REGB1 = TAG_Bool(UNTAG_Int(REGB0)<UNTAG_Int(REGB1));
  } else {
    /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
    REGB2 = TAG_Bool(false);
    REGB1 = REGB2;
  }
  if (UNTAG_Bool(REGB1)) {
  } else {
    nit_abort("Assert %s  failed", "'index'", LOCATE_array, 245);
  }
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
  fra.me.REG[11] = ATTR_array___Array____items(fra.me.REG[11]);
  REGB1 = TAG_Bool(fra.me.REG[11]==NIT_NULL);
  if (UNTAG_Bool(REGB1)) {
    nit_abort("Reciever is null", NULL, LOCATE_array, 246);
  }
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:654 */
  fra.me.REG[11] = ((Nit_NativeArray)fra.me.REG[11])->val[UNTAG_Int(REGB0)];
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
  goto label71;
  label71: while(0);
  /* ./test.nit:102 */
  REGB0 = TAG_Bool(fra.me.REG[11]==NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
    nit_abort("Reciever is null", NULL, LOCATE_test, 102);
  }
  fra.me.REG[11] = CALL_figure___Segment___taille(fra.me.REG[11])(fra.me.REG[11]);
  fra.me.REG[11] = CALL_string___Object___to_s(fra.me.REG[11])(fra.me.REG[11]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[11]);
  if (!once_value_72) {
    fra.me.REG[11] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[11] = NEW_String_string___String___with_native(fra.me.REG[11], REGB0);
    once_value_72 = fra.me.REG[11];
    register_static_object(&once_value_72);
  } else fra.me.REG[11] = once_value_72;
  fra.me.REG[11] = fra.me.REG[11];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[11]);
  fra.me.REG[7] = CALL_string___Object___to_s(fra.me.REG[7])(fra.me.REG[7]);
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
  /* ./test.nit:103 */
  REGB0 = TAG_Int(3);
  fra.me.REG[7] = NEW_Array_array___Array___with_capacity(REGB0);
  if (!once_value_73) {
    fra.me.REG[11] = BOX_NativeString("Diagonale d'un rectangle ");
    REGB0 = TAG_Int(25);
    fra.me.REG[11] = NEW_String_string___String___with_native(fra.me.REG[11], REGB0);
    once_value_73 = fra.me.REG[11];
    register_static_object(&once_value_73);
  } else fra.me.REG[11] = once_value_73;
  fra.me.REG[11] = fra.me.REG[11];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[11]);
  fra.me.REG[11] = CALL_polygone___Quadrilatere___diagonales(fra.me.REG[10])(fra.me.REG[10]);
  REGB0 = TAG_Int(0);
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
  REGB1 = TAG_Int(0);
  /* /Users/tony/Projects/nit/lib/standard//kernel.nit:213 */
  REGB1 = TAG_Bool(UNTAG_Int(REGB0)>=UNTAG_Int(REGB1));
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
  if (UNTAG_Bool(REGB1)) {
    REGB1 = TAG_Bool(ATTR_array___AbstractArrayRead____length(fra.me.REG[11])!=NIT_NULL);
    if (UNTAG_Bool(REGB1)) {
    } else {
      nit_abort("Uninitialized attribute %s", "_length", LOCATE_array, 245);
    }
    REGB1 = ATTR_array___AbstractArrayRead____length(fra.me.REG[11]);
    /* /Users/tony/Projects/nit/lib/standard//kernel.nit:212 */
    REGB1 = TAG_Bool(UNTAG_Int(REGB0)<UNTAG_Int(REGB1));
  } else {
    /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
    REGB2 = TAG_Bool(false);
    REGB1 = REGB2;
  }
  if (UNTAG_Bool(REGB1)) {
  } else {
    nit_abort("Assert %s  failed", "'index'", LOCATE_array, 245);
  }
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
  fra.me.REG[11] = ATTR_array___Array____items(fra.me.REG[11]);
  REGB1 = TAG_Bool(fra.me.REG[11]==NIT_NULL);
  if (UNTAG_Bool(REGB1)) {
    nit_abort("Reciever is null", NULL, LOCATE_array, 246);
  }
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:654 */
  fra.me.REG[11] = ((Nit_NativeArray)fra.me.REG[11])->val[UNTAG_Int(REGB0)];
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
  goto label74;
  label74: while(0);
  /* ./test.nit:103 */
  REGB0 = TAG_Bool(fra.me.REG[11]==NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
    nit_abort("Reciever is null", NULL, LOCATE_test, 103);
  }
  fra.me.REG[11] = CALL_figure___Segment___taille(fra.me.REG[11])(fra.me.REG[11]);
  fra.me.REG[11] = CALL_string___Object___to_s(fra.me.REG[11])(fra.me.REG[11]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[11]);
  if (!once_value_75) {
    fra.me.REG[11] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[11] = NEW_String_string___String___with_native(fra.me.REG[11], REGB0);
    once_value_75 = fra.me.REG[11];
    register_static_object(&once_value_75);
  } else fra.me.REG[11] = once_value_75;
  fra.me.REG[11] = fra.me.REG[11];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[11]);
  fra.me.REG[7] = CALL_string___Object___to_s(fra.me.REG[7])(fra.me.REG[7]);
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
  /* ./test.nit:105 */
  if (!once_value_76) {
    fra.me.REG[7] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[7] = NEW_String_string___String___with_native(fra.me.REG[7], REGB0);
    once_value_76 = fra.me.REG[7];
    register_static_object(&once_value_76);
  } else fra.me.REG[7] = once_value_76;
  fra.me.REG[7] = fra.me.REG[7];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
  /* ./test.nit:106 */
  if (!once_value_77) {
    fra.me.REG[7] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[7] = NEW_String_string___String___with_native(fra.me.REG[7], REGB0);
    once_value_77 = fra.me.REG[7];
    register_static_object(&once_value_77);
  } else fra.me.REG[7] = once_value_77;
  fra.me.REG[7] = fra.me.REG[7];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
  /* ./test.nit:109 */
  if (!once_value_78) {
    fra.me.REG[7] = BOX_NativeString("Obtenir la taille du coté et des deux diagonales d’un losange.");
    REGB0 = TAG_Int(65);
    fra.me.REG[7] = NEW_String_string___String___with_native(fra.me.REG[7], REGB0);
    once_value_78 = fra.me.REG[7];
    register_static_object(&once_value_78);
  } else fra.me.REG[7] = once_value_78;
  fra.me.REG[7] = fra.me.REG[7];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
  /* ./test.nit:110 */
  REGB0 = TAG_Int(3);
  fra.me.REG[7] = NEW_Array_array___Array___with_capacity(REGB0);
  if (!once_value_79) {
    fra.me.REG[11] = BOX_NativeString("Taille du coté d'un losange  ");
    REGB0 = TAG_Int(30);
    fra.me.REG[11] = NEW_String_string___String___with_native(fra.me.REG[11], REGB0);
    once_value_79 = fra.me.REG[11];
    register_static_object(&once_value_79);
  } else fra.me.REG[11] = once_value_79;
  fra.me.REG[11] = fra.me.REG[11];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[11]);
  fra.me.REG[11] = CALL_polygone___Polygone___cotes(fra.me.REG[9])(fra.me.REG[9]);
  REGB0 = TAG_Int(0);
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
  REGB1 = TAG_Int(0);
  /* /Users/tony/Projects/nit/lib/standard//kernel.nit:213 */
  REGB1 = TAG_Bool(UNTAG_Int(REGB0)>=UNTAG_Int(REGB1));
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
  if (UNTAG_Bool(REGB1)) {
    REGB1 = TAG_Bool(ATTR_array___AbstractArrayRead____length(fra.me.REG[11])!=NIT_NULL);
    if (UNTAG_Bool(REGB1)) {
    } else {
      nit_abort("Uninitialized attribute %s", "_length", LOCATE_array, 245);
    }
    REGB1 = ATTR_array___AbstractArrayRead____length(fra.me.REG[11]);
    /* /Users/tony/Projects/nit/lib/standard//kernel.nit:212 */
    REGB1 = TAG_Bool(UNTAG_Int(REGB0)<UNTAG_Int(REGB1));
  } else {
    /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
    REGB2 = TAG_Bool(false);
    REGB1 = REGB2;
  }
  if (UNTAG_Bool(REGB1)) {
  } else {
    nit_abort("Assert %s  failed", "'index'", LOCATE_array, 245);
  }
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
  fra.me.REG[11] = ATTR_array___Array____items(fra.me.REG[11]);
  REGB1 = TAG_Bool(fra.me.REG[11]==NIT_NULL);
  if (UNTAG_Bool(REGB1)) {
    nit_abort("Reciever is null", NULL, LOCATE_array, 246);
  }
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:654 */
  fra.me.REG[11] = ((Nit_NativeArray)fra.me.REG[11])->val[UNTAG_Int(REGB0)];
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
  goto label80;
  label80: while(0);
  /* ./test.nit:110 */
  REGB0 = TAG_Bool(fra.me.REG[11]==NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
    nit_abort("Reciever is null", NULL, LOCATE_test, 110);
  }
  fra.me.REG[11] = CALL_figure___Segment___taille(fra.me.REG[11])(fra.me.REG[11]);
  fra.me.REG[11] = CALL_string___Object___to_s(fra.me.REG[11])(fra.me.REG[11]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[11]);
  if (!once_value_81) {
    fra.me.REG[11] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[11] = NEW_String_string___String___with_native(fra.me.REG[11], REGB0);
    once_value_81 = fra.me.REG[11];
    register_static_object(&once_value_81);
  } else fra.me.REG[11] = once_value_81;
  fra.me.REG[11] = fra.me.REG[11];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[11]);
  fra.me.REG[7] = CALL_string___Object___to_s(fra.me.REG[7])(fra.me.REG[7]);
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
  /* ./test.nit:111 */
  REGB0 = TAG_Int(3);
  fra.me.REG[7] = NEW_Array_array___Array___with_capacity(REGB0);
  if (!once_value_82) {
    fra.me.REG[11] = BOX_NativeString("Taille de la première diagonale d'un losange  ");
    REGB0 = TAG_Int(47);
    fra.me.REG[11] = NEW_String_string___String___with_native(fra.me.REG[11], REGB0);
    once_value_82 = fra.me.REG[11];
    register_static_object(&once_value_82);
  } else fra.me.REG[11] = once_value_82;
  fra.me.REG[11] = fra.me.REG[11];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[11]);
  fra.me.REG[11] = CALL_polygone___Polygone___cotes(fra.me.REG[9])(fra.me.REG[9]);
  REGB0 = TAG_Int(0);
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
  REGB1 = TAG_Int(0);
  /* /Users/tony/Projects/nit/lib/standard//kernel.nit:213 */
  REGB1 = TAG_Bool(UNTAG_Int(REGB0)>=UNTAG_Int(REGB1));
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
  if (UNTAG_Bool(REGB1)) {
    REGB1 = TAG_Bool(ATTR_array___AbstractArrayRead____length(fra.me.REG[11])!=NIT_NULL);
    if (UNTAG_Bool(REGB1)) {
    } else {
      nit_abort("Uninitialized attribute %s", "_length", LOCATE_array, 245);
    }
    REGB1 = ATTR_array___AbstractArrayRead____length(fra.me.REG[11]);
    /* /Users/tony/Projects/nit/lib/standard//kernel.nit:212 */
    REGB1 = TAG_Bool(UNTAG_Int(REGB0)<UNTAG_Int(REGB1));
  } else {
    /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
    REGB2 = TAG_Bool(false);
    REGB1 = REGB2;
  }
  if (UNTAG_Bool(REGB1)) {
  } else {
    nit_abort("Assert %s  failed", "'index'", LOCATE_array, 245);
  }
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
  fra.me.REG[11] = ATTR_array___Array____items(fra.me.REG[11]);
  REGB1 = TAG_Bool(fra.me.REG[11]==NIT_NULL);
  if (UNTAG_Bool(REGB1)) {
    nit_abort("Reciever is null", NULL, LOCATE_array, 246);
  }
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:654 */
  fra.me.REG[11] = ((Nit_NativeArray)fra.me.REG[11])->val[UNTAG_Int(REGB0)];
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
  goto label83;
  label83: while(0);
  /* ./test.nit:111 */
  REGB0 = TAG_Bool(fra.me.REG[11]==NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
    nit_abort("Reciever is null", NULL, LOCATE_test, 111);
  }
  fra.me.REG[11] = CALL_figure___Segment___taille(fra.me.REG[11])(fra.me.REG[11]);
  fra.me.REG[11] = CALL_string___Object___to_s(fra.me.REG[11])(fra.me.REG[11]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[11]);
  if (!once_value_84) {
    fra.me.REG[11] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[11] = NEW_String_string___String___with_native(fra.me.REG[11], REGB0);
    once_value_84 = fra.me.REG[11];
    register_static_object(&once_value_84);
  } else fra.me.REG[11] = once_value_84;
  fra.me.REG[11] = fra.me.REG[11];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[11]);
  fra.me.REG[7] = CALL_string___Object___to_s(fra.me.REG[7])(fra.me.REG[7]);
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
  /* ./test.nit:112 */
  REGB0 = TAG_Int(3);
  fra.me.REG[7] = NEW_Array_array___Array___with_capacity(REGB0);
  if (!once_value_85) {
    fra.me.REG[11] = BOX_NativeString("Taille de la deuxième diagonales d'un losange  ");
    REGB0 = TAG_Int(48);
    fra.me.REG[11] = NEW_String_string___String___with_native(fra.me.REG[11], REGB0);
    once_value_85 = fra.me.REG[11];
    register_static_object(&once_value_85);
  } else fra.me.REG[11] = once_value_85;
  fra.me.REG[11] = fra.me.REG[11];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[11]);
  fra.me.REG[11] = CALL_polygone___Polygone___cotes(fra.me.REG[9])(fra.me.REG[9]);
  REGB0 = TAG_Int(1);
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
  REGB1 = TAG_Int(0);
  /* /Users/tony/Projects/nit/lib/standard//kernel.nit:213 */
  REGB1 = TAG_Bool(UNTAG_Int(REGB0)>=UNTAG_Int(REGB1));
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
  if (UNTAG_Bool(REGB1)) {
    REGB1 = TAG_Bool(ATTR_array___AbstractArrayRead____length(fra.me.REG[11])!=NIT_NULL);
    if (UNTAG_Bool(REGB1)) {
    } else {
      nit_abort("Uninitialized attribute %s", "_length", LOCATE_array, 245);
    }
    REGB1 = ATTR_array___AbstractArrayRead____length(fra.me.REG[11]);
    /* /Users/tony/Projects/nit/lib/standard//kernel.nit:212 */
    REGB1 = TAG_Bool(UNTAG_Int(REGB0)<UNTAG_Int(REGB1));
  } else {
    /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:245 */
    REGB2 = TAG_Bool(false);
    REGB1 = REGB2;
  }
  if (UNTAG_Bool(REGB1)) {
  } else {
    nit_abort("Assert %s  failed", "'index'", LOCATE_array, 245);
  }
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
  fra.me.REG[11] = ATTR_array___Array____items(fra.me.REG[11]);
  REGB1 = TAG_Bool(fra.me.REG[11]==NIT_NULL);
  if (UNTAG_Bool(REGB1)) {
    nit_abort("Reciever is null", NULL, LOCATE_array, 246);
  }
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:654 */
  fra.me.REG[11] = ((Nit_NativeArray)fra.me.REG[11])->val[UNTAG_Int(REGB0)];
  /* /Users/tony/Projects/nit/lib/standard//collection//array.nit:246 */
  goto label86;
  label86: while(0);
  /* ./test.nit:112 */
  REGB0 = TAG_Bool(fra.me.REG[11]==NIT_NULL);
  if (UNTAG_Bool(REGB0)) {
    nit_abort("Reciever is null", NULL, LOCATE_test, 112);
  }
  fra.me.REG[11] = CALL_figure___Segment___taille(fra.me.REG[11])(fra.me.REG[11]);
  fra.me.REG[11] = CALL_string___Object___to_s(fra.me.REG[11])(fra.me.REG[11]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[11]);
  if (!once_value_87) {
    fra.me.REG[11] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[11] = NEW_String_string___String___with_native(fra.me.REG[11], REGB0);
    once_value_87 = fra.me.REG[11];
    register_static_object(&once_value_87);
  } else fra.me.REG[11] = once_value_87;
  fra.me.REG[11] = fra.me.REG[11];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[11]);
  fra.me.REG[7] = CALL_string___Object___to_s(fra.me.REG[7])(fra.me.REG[7]);
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
  /* ./test.nit:114 */
  if (!once_value_88) {
    fra.me.REG[7] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[7] = NEW_String_string___String___with_native(fra.me.REG[7], REGB0);
    once_value_88 = fra.me.REG[7];
    register_static_object(&once_value_88);
  } else fra.me.REG[7] = once_value_88;
  fra.me.REG[7] = fra.me.REG[7];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
  /* ./test.nit:115 */
  if (!once_value_89) {
    fra.me.REG[7] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[7] = NEW_String_string___String___with_native(fra.me.REG[7], REGB0);
    once_value_89 = fra.me.REG[7];
    register_static_object(&once_value_89);
  } else fra.me.REG[7] = once_value_89;
  fra.me.REG[7] = fra.me.REG[7];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
  /* ./test.nit:117 */
  if (!once_value_90) {
    fra.me.REG[7] = BOX_NativeString("Obtenir le cercle circonscrit d’un rectangle (cercle passant par les quatre sommets).");
    REGB0 = TAG_Int(87);
    fra.me.REG[7] = NEW_String_string___String___with_native(fra.me.REG[7], REGB0);
    once_value_90 = fra.me.REG[7];
    register_static_object(&once_value_90);
  } else fra.me.REG[7] = once_value_90;
  fra.me.REG[7] = fra.me.REG[7];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
  /* ./test.nit:118 */
  REGB0 = TAG_Int(3);
  fra.me.REG[7] = NEW_Array_array___Array___with_capacity(REGB0);
  if (!once_value_91) {
    fra.me.REG[11] = BOX_NativeString("Cercle circonscrit  ");
    REGB0 = TAG_Int(20);
    fra.me.REG[11] = NEW_String_string___String___with_native(fra.me.REG[11], REGB0);
    once_value_91 = fra.me.REG[11];
    register_static_object(&once_value_91);
  } else fra.me.REG[11] = once_value_91;
  fra.me.REG[11] = fra.me.REG[11];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[11]);
  fra.me.REG[11] = CALL_polygone___Rectangle___cercleCirconscrit(fra.me.REG[10])(fra.me.REG[10]);
  fra.me.REG[11] = CALL_string___Object___to_s(fra.me.REG[11])(fra.me.REG[11]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[11]);
  if (!once_value_92) {
    fra.me.REG[11] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[11] = NEW_String_string___String___with_native(fra.me.REG[11], REGB0);
    once_value_92 = fra.me.REG[11];
    register_static_object(&once_value_92);
  } else fra.me.REG[11] = once_value_92;
  fra.me.REG[11] = fra.me.REG[11];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[11]);
  fra.me.REG[7] = CALL_string___Object___to_s(fra.me.REG[7])(fra.me.REG[7]);
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
  /* ./test.nit:120 */
  if (!once_value_93) {
    fra.me.REG[7] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[7] = NEW_String_string___String___with_native(fra.me.REG[7], REGB0);
    once_value_93 = fra.me.REG[7];
    register_static_object(&once_value_93);
  } else fra.me.REG[7] = once_value_93;
  fra.me.REG[7] = fra.me.REG[7];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
  /* ./test.nit:121 */
  if (!once_value_94) {
    fra.me.REG[7] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[7] = NEW_String_string___String___with_native(fra.me.REG[7], REGB0);
    once_value_94 = fra.me.REG[7];
    register_static_object(&once_value_94);
  } else fra.me.REG[7] = once_value_94;
  fra.me.REG[7] = fra.me.REG[7];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
  /* ./test.nit:123 */
  if (!once_value_95) {
    fra.me.REG[7] = BOX_NativeString("Obtenir le cercle inscrit d’un losange (cercle tangent aux quatre cotés).");
    REGB0 = TAG_Int(76);
    fra.me.REG[7] = NEW_String_string___String___with_native(fra.me.REG[7], REGB0);
    once_value_95 = fra.me.REG[7];
    register_static_object(&once_value_95);
  } else fra.me.REG[7] = once_value_95;
  fra.me.REG[7] = fra.me.REG[7];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
  /* ./test.nit:124 */
  REGB0 = TAG_Int(3);
  fra.me.REG[7] = NEW_Array_array___Array___with_capacity(REGB0);
  if (!once_value_96) {
    fra.me.REG[11] = BOX_NativeString("Cercle inscrit  ");
    REGB0 = TAG_Int(16);
    fra.me.REG[11] = NEW_String_string___String___with_native(fra.me.REG[11], REGB0);
    once_value_96 = fra.me.REG[11];
    register_static_object(&once_value_96);
  } else fra.me.REG[11] = once_value_96;
  fra.me.REG[11] = fra.me.REG[11];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[11]);
  fra.me.REG[11] = CALL_polygone___Losange___cercleInscrit(fra.me.REG[9])(fra.me.REG[9]);
  fra.me.REG[11] = CALL_string___Object___to_s(fra.me.REG[11])(fra.me.REG[11]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[11]);
  if (!once_value_97) {
    fra.me.REG[11] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[11] = NEW_String_string___String___with_native(fra.me.REG[11], REGB0);
    once_value_97 = fra.me.REG[11];
    register_static_object(&once_value_97);
  } else fra.me.REG[11] = once_value_97;
  fra.me.REG[11] = fra.me.REG[11];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[11]);
  fra.me.REG[7] = CALL_string___Object___to_s(fra.me.REG[7])(fra.me.REG[7]);
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
  /* ./test.nit:126 */
  if (!once_value_98) {
    fra.me.REG[7] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[7] = NEW_String_string___String___with_native(fra.me.REG[7], REGB0);
    once_value_98 = fra.me.REG[7];
    register_static_object(&once_value_98);
  } else fra.me.REG[7] = once_value_98;
  fra.me.REG[7] = fra.me.REG[7];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
  /* ./test.nit:127 */
  if (!once_value_99) {
    fra.me.REG[7] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[7] = NEW_String_string___String___with_native(fra.me.REG[7], REGB0);
    once_value_99 = fra.me.REG[7];
    register_static_object(&once_value_99);
  } else fra.me.REG[7] = once_value_99;
  fra.me.REG[7] = fra.me.REG[7];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
  /* ./test.nit:129 */
  if (!once_value_100) {
    fra.me.REG[7] = BOX_NativeString("Obtenir le rectangle inscrit dans un cercle étant donnés deux sommets adjacents situés sur le cercle.");
    REGB0 = TAG_Int(104);
    fra.me.REG[7] = NEW_String_string___String___with_native(fra.me.REG[7], REGB0);
    once_value_100 = fra.me.REG[7];
    register_static_object(&once_value_100);
  } else fra.me.REG[7] = once_value_100;
  fra.me.REG[7] = fra.me.REG[7];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
  /* ./test.nit:130 */
  REGB0 = TAG_Int(3);
  fra.me.REG[7] = NEW_Array_array___Array___with_capacity(REGB0);
  if (!once_value_101) {
    fra.me.REG[11] = BOX_NativeString("Rectangle inscrit d'un rectangle  ");
    REGB0 = TAG_Int(34);
    fra.me.REG[11] = NEW_String_string___String___with_native(fra.me.REG[11], REGB0);
    once_value_101 = fra.me.REG[11];
    register_static_object(&once_value_101);
  } else fra.me.REG[11] = once_value_101;
  fra.me.REG[11] = fra.me.REG[11];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[11]);
  fra.me.REG[11] = CALL_polygone___Losange___rectangleInscrit(fra.me.REG[9])(fra.me.REG[9]);
  fra.me.REG[11] = CALL_string___Object___to_s(fra.me.REG[11])(fra.me.REG[11]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[11]);
  if (!once_value_102) {
    fra.me.REG[11] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[11] = NEW_String_string___String___with_native(fra.me.REG[11], REGB0);
    once_value_102 = fra.me.REG[11];
    register_static_object(&once_value_102);
  } else fra.me.REG[11] = once_value_102;
  fra.me.REG[11] = fra.me.REG[11];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[11]);
  fra.me.REG[7] = CALL_string___Object___to_s(fra.me.REG[7])(fra.me.REG[7]);
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
  /* ./test.nit:132 */
  if (!once_value_103) {
    fra.me.REG[7] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[7] = NEW_String_string___String___with_native(fra.me.REG[7], REGB0);
    once_value_103 = fra.me.REG[7];
    register_static_object(&once_value_103);
  } else fra.me.REG[7] = once_value_103;
  fra.me.REG[7] = fra.me.REG[7];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
  /* ./test.nit:133 */
  if (!once_value_104) {
    fra.me.REG[7] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[7] = NEW_String_string___String___with_native(fra.me.REG[7], REGB0);
    once_value_104 = fra.me.REG[7];
    register_static_object(&once_value_104);
  } else fra.me.REG[7] = once_value_104;
  fra.me.REG[7] = fra.me.REG[7];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
  /* ./test.nit:135 */
  if (!once_value_105) {
    fra.me.REG[7] = BOX_NativeString("Obtenir le rectangle inscrit d’un losange et le losange inscrit d’un rectangle.");
    REGB0 = TAG_Int(83);
    fra.me.REG[7] = NEW_String_string___String___with_native(fra.me.REG[7], REGB0);
    once_value_105 = fra.me.REG[7];
    register_static_object(&once_value_105);
  } else fra.me.REG[7] = once_value_105;
  fra.me.REG[7] = fra.me.REG[7];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
  /* ./test.nit:136 */
  REGB0 = TAG_Int(3);
  fra.me.REG[7] = NEW_Array_array___Array___with_capacity(REGB0);
  if (!once_value_106) {
    fra.me.REG[11] = BOX_NativeString("Rectangle inscrit d'un losange  ");
    REGB0 = TAG_Int(32);
    fra.me.REG[11] = NEW_String_string___String___with_native(fra.me.REG[11], REGB0);
    once_value_106 = fra.me.REG[11];
    register_static_object(&once_value_106);
  } else fra.me.REG[11] = once_value_106;
  fra.me.REG[11] = fra.me.REG[11];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[11]);
  fra.me.REG[11] = CALL_polygone___Losange___rectangleInscrit(fra.me.REG[9])(fra.me.REG[9]);
  fra.me.REG[11] = CALL_string___Object___to_s(fra.me.REG[11])(fra.me.REG[11]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[11]);
  if (!once_value_107) {
    fra.me.REG[11] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[11] = NEW_String_string___String___with_native(fra.me.REG[11], REGB0);
    once_value_107 = fra.me.REG[11];
    register_static_object(&once_value_107);
  } else fra.me.REG[11] = once_value_107;
  fra.me.REG[11] = fra.me.REG[11];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[11]);
  fra.me.REG[7] = CALL_string___Object___to_s(fra.me.REG[7])(fra.me.REG[7]);
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
  /* ./test.nit:137 */
  REGB0 = TAG_Int(3);
  fra.me.REG[7] = NEW_Array_array___Array___with_capacity(REGB0);
  if (!once_value_108) {
    fra.me.REG[11] = BOX_NativeString("Losange inscrit d'un rectangle  ");
    REGB0 = TAG_Int(32);
    fra.me.REG[11] = NEW_String_string___String___with_native(fra.me.REG[11], REGB0);
    once_value_108 = fra.me.REG[11];
    register_static_object(&once_value_108);
  } else fra.me.REG[11] = once_value_108;
  fra.me.REG[11] = fra.me.REG[11];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[11]);
  fra.me.REG[11] = CALL_polygone___Rectangle___losangeInscrit(fra.me.REG[10])(fra.me.REG[10]);
  fra.me.REG[11] = CALL_string___Object___to_s(fra.me.REG[11])(fra.me.REG[11]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[11]);
  if (!once_value_109) {
    fra.me.REG[11] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[11] = NEW_String_string___String___with_native(fra.me.REG[11], REGB0);
    once_value_109 = fra.me.REG[11];
    register_static_object(&once_value_109);
  } else fra.me.REG[11] = once_value_109;
  fra.me.REG[11] = fra.me.REG[11];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[11]);
  fra.me.REG[7] = CALL_string___Object___to_s(fra.me.REG[7])(fra.me.REG[7]);
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
  /* ./test.nit:139 */
  if (!once_value_110) {
    fra.me.REG[7] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[7] = NEW_String_string___String___with_native(fra.me.REG[7], REGB0);
    once_value_110 = fra.me.REG[7];
    register_static_object(&once_value_110);
  } else fra.me.REG[7] = once_value_110;
  fra.me.REG[7] = fra.me.REG[7];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
  /* ./test.nit:140 */
  if (!once_value_111) {
    fra.me.REG[7] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[7] = NEW_String_string___String___with_native(fra.me.REG[7], REGB0);
    once_value_111 = fra.me.REG[7];
    register_static_object(&once_value_111);
  } else fra.me.REG[7] = once_value_111;
  fra.me.REG[7] = fra.me.REG[7];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
  /* ./test.nit:142 */
  if (!once_value_112) {
    fra.me.REG[7] = BOX_NativeString("Savoir si deux figures sont géométriquement les mêmes.");
    REGB0 = TAG_Int(57);
    fra.me.REG[7] = NEW_String_string___String___with_native(fra.me.REG[7], REGB0);
    once_value_112 = fra.me.REG[7];
    register_static_object(&once_value_112);
  } else fra.me.REG[7] = once_value_112;
  fra.me.REG[7] = fra.me.REG[7];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
  /* ./test.nit:143 */
  REGB0 = TAG_Int(3);
  fra.me.REG[7] = NEW_Array_array___Array___with_capacity(REGB0);
  if (!once_value_113) {
    fra.me.REG[11] = BOX_NativeString("Losange et Rectangle identiques ?: ");
    REGB0 = TAG_Int(35);
    fra.me.REG[11] = NEW_String_string___String___with_native(fra.me.REG[11], REGB0);
    once_value_113 = fra.me.REG[11];
    register_static_object(&once_value_113);
  } else fra.me.REG[11] = once_value_113;
  fra.me.REG[11] = fra.me.REG[11];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[11]);
  REGB0 = TAG_Bool(IS_EQUAL_OO(fra.me.REG[9],fra.me.REG[10]));
  if (UNTAG_Bool(REGB0)) {
  } else {
    REGB1 = CALL_kernel___Object_____eqeq(fra.me.REG[9])(fra.me.REG[9], fra.me.REG[10]);
    REGB0 = REGB1;
  }
  fra.me.REG[10] = CALL_string___Object___to_s(REGB0)(REGB0);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[10]);
  if (!once_value_114) {
    fra.me.REG[10] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[10] = NEW_String_string___String___with_native(fra.me.REG[10], REGB0);
    once_value_114 = fra.me.REG[10];
    register_static_object(&once_value_114);
  } else fra.me.REG[10] = once_value_114;
  fra.me.REG[10] = fra.me.REG[10];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[10]);
  fra.me.REG[7] = CALL_string___Object___to_s(fra.me.REG[7])(fra.me.REG[7]);
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
  /* ./test.nit:145 */
  if (!once_value_115) {
    fra.me.REG[7] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[7] = NEW_String_string___String___with_native(fra.me.REG[7], REGB0);
    once_value_115 = fra.me.REG[7];
    register_static_object(&once_value_115);
  } else fra.me.REG[7] = once_value_115;
  fra.me.REG[7] = fra.me.REG[7];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
  /* ./test.nit:146 */
  if (!once_value_116) {
    fra.me.REG[7] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[7] = NEW_String_string___String___with_native(fra.me.REG[7], REGB0);
    once_value_116 = fra.me.REG[7];
    register_static_object(&once_value_116);
  } else fra.me.REG[7] = once_value_116;
  fra.me.REG[7] = fra.me.REG[7];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[7]);
  /* ./test.nit:148 */
  fra.me.REG[7] = NEW_Fabrique_factory___Fabrique___init();
  /* ./test.nit:149 */
  if (!once_value_117) {
    fra.me.REG[10] = BOX_NativeString("Utilisation de la classe Fabrique");
    REGB0 = TAG_Int(33);
    fra.me.REG[10] = NEW_String_string___String___with_native(fra.me.REG[10], REGB0);
    once_value_117 = fra.me.REG[10];
    register_static_object(&once_value_117);
  } else fra.me.REG[10] = once_value_117;
  fra.me.REG[10] = fra.me.REG[10];
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[10]);
  /* ./test.nit:150 */
  REGB0 = TAG_Int(3);
  fra.me.REG[10] = NEW_Array_array___Array___with_capacity(REGB0);
  if (!once_value_118) {
    fra.me.REG[9] = BOX_NativeString("Construction d'un polygone avec 4 points: ");
    REGB0 = TAG_Int(42);
    fra.me.REG[9] = NEW_String_string___String___with_native(fra.me.REG[9], REGB0);
    once_value_118 = fra.me.REG[9];
    register_static_object(&once_value_118);
  } else fra.me.REG[9] = once_value_118;
  fra.me.REG[9] = fra.me.REG[9];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[10])(fra.me.REG[10], fra.me.REG[9]);
  REGB0 = TAG_Int(4);
  fra.me.REG[9] = NEW_Array_array___Array___with_capacity(REGB0);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[9])(fra.me.REG[9], fra.me.REG[2]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[9])(fra.me.REG[9], fra.me.REG[3]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[9])(fra.me.REG[9], fra.me.REG[4]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[9])(fra.me.REG[9], fra.me.REG[5]);
  fra.me.REG[9] = CALL_factory___Fabrique___creerPolygone(fra.me.REG[7])(fra.me.REG[7], fra.me.REG[9]);
  fra.me.REG[9] = CALL_string___Object___to_s(fra.me.REG[9])(fra.me.REG[9]);
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[10])(fra.me.REG[10], fra.me.REG[9]);
  if (!once_value_119) {
    fra.me.REG[9] = BOX_NativeString("");
    REGB0 = TAG_Int(0);
    fra.me.REG[9] = NEW_String_string___String___with_native(fra.me.REG[9], REGB0);
    once_value_119 = fra.me.REG[9];
    register_static_object(&once_value_119);
  } else fra.me.REG[9] = once_value_119;
  fra.me.REG[9] = fra.me.REG[9];
  CALL_abstract_collection___SimpleCollection___add(fra.me.REG[10])(fra.me.REG[10], fra.me.REG[9]);
  fra.me.REG[10] = CALL_string___Object___to_s(fra.me.REG[10])(fra.me.REG[10]);
  CALL_file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[10]);
  stack_frame_head = fra.me.prev;
  return;
}
