/* This C header file is generated by NIT to compile modules and programs that requires test. */
#ifndef test_sep
#define test_sep
#include "factory._sep.h"
#include <nit_common.h>
extern const char *LOCATE_test;
extern const int SFT_test[];
static const char * const LOCATE_test___Sys___main = "test::Sys::(kernel::Sys::main)";
void test___Sys___main(val_t p0);
typedef void (*test___Sys___main_t)(val_t p0);
val_t NEW_Sys_kernel___Sys___init();
#endif
