/* This C header file is generated by NIT to compile modules and programs that requires utils. */
#ifndef utils_sep
#define utils_sep
#include "standard._sep.h"
#include <nit_common.h>
extern const char *LOCATE_utils;
extern const int SFT_utils[];
#define CALL_utils___Float___absolue(recv) ((utils___Float___absolue_t)CALL((recv), (SFT_utils[0] + 0)))
static const char * const LOCATE_utils___Float___absolue = "utils::Float::absolue";
val_t utils___Float___absolue(val_t p0);
typedef val_t (*utils___Float___absolue_t)(val_t p0);
#endif
